### ISSUE TITLE
Error: http://LAN_IP:8888/{canal}/live - 404 Not found

### ISSUE THREAD

**Issue by jagbarcelo** [jmarcet/movistar-u7d#10]
Sigo intentando poner en marcha tu proyecto en una Raspberry Pi 4 con Ubuntu Server 20.10 de 64bits.

Después de tus correcciones en [sanic-prometeus](https://github.com/jmarcet/sanic-prometheus), ahora el microservicio de la EPG funciona bien. Sin embargo el proxy para reproducir canales no. Si por ejemplo en el reproductor VLC introduzco la url http://192.168.1.8:8888/4455/live (correspondiente a **La2**), no me aparece ningún stream.

El registro en `/var/log/syslog` de esa consulta es el siguiente:

```
Jan  6 00:56:15 pi-u7d movistar_u7d.py[1813]: [2022-01-06 00:56:15] [1813] [ERROR] /4455/live not found
Jan  6 00:56:15 pi-u7d movistar_u7d.py[1813]: [2022-01-06 00:56:15] [1813] [ERROR] /4455/live not found
```

![image](https://user-images.githubusercontent.com/6704109/148307280-82cc0645-3c16-4eed-a92e-b6bbd42f3de7.png)

En este caso no tengo ni idea de por donde empezar a tirar del hilo...

**Comment by jmarcet** [comment]
Hmm, está funcionando correctamente el movistar_epg.py? Ha generado correctamente la lista de canales y la guía?

Para poder acceder a los directos es esencial que exista `${HOME}/.xmltv/cache/epg_metadata.json`, así como para el catchup es esencial `${HOME}/.xmltv/cache/epg.json`. Ambos son generados por `tv_grab_movistartv` como paso previo a generar la lista de canales y la guía.

Puedes mirar el contenido de `${HOME}/.xmltv/tv_grab_es_movistartv.log` además del syslog?

Si todas esas piezas son correctas, en principio sólo puede dar ese error por no recibir el multicast, pero es algo en sí necesario para generar todo lo anterior.

**Comment by jagbarcelo** [comment]
Si, los ficheros `guide.xml` y `MovistarTV.m3u` se generan correctamente en `/home`:

```
root@pi-u7d:/home# head MovistarTV.m3u
#EXTM3U name="MovistarTV" catchup="flussonic" catchup-days=8 dlna_extras=mpeg_ps_pal url-tvg="http://192.168.1.8:8888/guide.xml"
#EXTINF:-1 tvg-chnum="1" tvg-id="2543.movistar.tv" group-title="IPTV - TDT Movistar.es" tvg-logo="http://192.168.1.8:8888/Logos/2543.jpg" catchup-source="http://192.168.1.8:8888/2543/{utc}-{duration}.ts",La 1 HD
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.stream_mode=timeshift
#KODIPROP:inputstream.ffmpegdirect.is_realtime_stream=true
http://192.168.1.8:8888/2543/live
#EXTINF:-1 tvg-chnum="2" tvg-id="4455.movistar.tv" group-title="IPTV - TDT Movistar.es" tvg-logo="http://192.168.1.8:8888/Logos/4455.jpg" catchup-source="http://192.168.1.8:8888/4455/{utc}-{duration}.ts",La 2 HD
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.stream_mode=timeshift
#KODIPROP:inputstream.ffmpegdirect.is_realtime_stream=true
root@pi-u7d:/home#
```

El fichero `/home/.xmltv/cache/epg_metadata.json` también existe y aparentemente tiene contenidos correctos:

```
root@pi-u7d:/home/.xmltv/cache# head epg_metadata.json
{
    "data": {
        "channels": {
            "1": {
                "address": "239.0.0.76",
                "genre": "Ocio y cultura",
                "id": "1",
                "logo_uri": "1.jpg",
                "name": "La 1",
                "port": "8208",
root@pi-u7d:/home/.xmltv/cache# tail epg_metadata.json
                    "0xff94": "1",
                    "0xff95": "1",
                    "0xff9b": "1",
                    "0xffdf": "1"
                },
                "Source": "EPG_7_BIN.imagenio.es"
            }
        }
    }
}
```

En el fichero `tv_grab_es_movistartv.log` no hay ningún mensaje de error (no aparece la palabra ERROR por ningún lado):

```
[...]
[2022-01-06 09:39:32] [INFO] ---------------------------------------------------
[2022-01-06 09:39:34] [INFO] tvPackages: UTX90|UTXAD|UTXAT
[2022-01-06 09:39:34] [INFO] Demarcation: 12
[2022-01-06 09:39:34] [INFO] Buscando el Proveedor de Servicios de Murcia
[2022-01-06 09:39:34] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[2022-01-06 09:40:12] [INFO] 239.0.2.148:3937 -> XML descargado
[2022-01-06 09:40:12] [INFO] Ficheros XML descargados: [2_0 5_0 6_0] / [2_0 5_0 6_0]
[2022-01-06 09:40:12] [INFO] Descargando canales y paquetes
[2022-01-06 09:40:12] [INFO] Canales: 448
[2022-01-06 09:40:12] [INFO] Paquetes: 374
[2022-01-06 09:40:12] [INFO] Descargando índices
[2022-01-06 09:40:12] [INFO] Días de EPG: 8
[2022-01-06 09:40:13] [INFO] Conservando 28 canales en abierto
[2022-01-06 09:40:13] [INFO] Multithread: 4 descargas simultáneas
[2022-01-06 09:40:13] [INFO] Descargando XML EPG_0_BIN -> 239.0.2.130:3937
[2022-01-06 09:40:13] [INFO] Descargando XML EPG_1_BIN -> 239.0.2.131:3937
[2022-01-06 09:40:13] [INFO] Descargando XML EPG_2_BIN -> 239.0.2.132:3937
[2022-01-06 09:40:13] [INFO] Descargando XML EPG_3_BIN -> 239.0.2.133:3937
[2022-01-06 09:40:30] [INFO] 239.0.2.130:3937 -> XML descargado
[2022-01-06 09:40:30] [INFO] Descargando XML EPG_4_BIN -> 239.0.2.134:3937
```

El listado de lo que hay en estos directorios de interés:

```
root@pi-u7d:/home# ls -l
total 9936
-rw-r--r-- 1 root   root      11218 Jan  6 09:43 MovistarTV.m3u
-rw-r--r-- 1 root   root   10157551 Jan  6 09:43 guide.xml
drwxr-x--- 6 ubuntu ubuntu     4096 Jan  6 00:46 ubuntu
root@pi-u7d:/home# cd .xmltv/
root@pi-u7d:/home/.xmltv# ls -l
total 192
drwxr-xr-x 3 root root   4096 Jan  5 19:47 cache
-rw-r--r-- 1 root root 186053 Jan  6 09:43 tv_grab_es_movistartv.log
root@pi-u7d:/home/.xmltv# cd cache
root@pi-u7d:/home/.xmltv/cache# ls -l
total 6832
-rw-r--r-- 1 root root   14083 Jan  5 18:30 config.json
-rw-r--r-- 1 root root 5718734 Jan  6 09:43 epg.json
-rw-r--r-- 1 root root  883396 Jan  6 09:40 epg_metadata.json
drwxr-xr-x 2 root root  356352 Jan  6 09:43 programs
-rw-r--r-- 1 root root      88 Jan  5 18:30 provider.json
-rw-r--r-- 1 root root      96 Jan  6 02:43 tv_grab_es_movistartv.cookie
-rw-r--r-- 1 root root     792 Jan  5 18:30 tv_grab_es_movistartv.endpoints
root@pi-u7d:/home/.xmltv/cache#
```
La RaspberryPi 4 ha estado corriendo toda la noche y algunos de esos ficheros tienen fecha/hora reciente, por lo que las programaciones para regenerarlos también se están disparando correctamente. Lo que no funciona son los canales en directo.

Cuando en tu documentación de [instalación](https://github.com/jmarcet/movistar-u7d#instalaci%C3%B3n) dices que 

> necesitamos algún dispositivo, sea un ordenador tradicional o algo más sencillo **como una raspberry**

¿Lo has llegado a probar tu o ha sido sólo una suposición? Realmente no veo porqué no iba a funcionar en una RBPi4, ahora que hasta tienen 8Gb de RAM y GPU con aceleración por hw (aunque no se si estará bien configurada esa parte todavía).

A mi entender, para que funcionen los canales en directo, le basta con hacer de proxy del flujo multicast que debería recibir de Movistar, ¿no?

**Comment by jmarcet** [comment]
No entiendo qué te está fallando. Por lo que me muestras toda la parte del EPG está funcionando correctamente, se actualiza la guía, etc.

Para acceder a los canales en directo, `movistar_u7d.py` es autónomo. Al iniciarse lee el fichero `epg_metadata.json` con el que obtiene la URL correcta de cada canal. El error `not found` que muestras sólo lo da cuando o no encuentra el número de canal en el fichero de metadatos, [aquí](https://github.com/jmarcet/movistar-u7d/blob/2bbf89a5a4edc592d2a5a2588ee76a76d7fa5611/movistar_u7d.py#L247), o justo a continuación por no recibir nada de la subscripción multicast [aquí](https://github.com/jmarcet/movistar-u7d/blob/2bbf89a5a4edc592d2a5a2588ee76a76d7fa5611/movistar_u7d.py#L267).

Para el catchup sí debe poder comunicarse con `movistar_epg.py`, pero para los directos no necesita nada más. Por algún motivo no le llega el multicast de los canales, no sé decirte por qué.

Aquí puedes verlo funcionando todo con VLC como cliente desde W11:

![image](https://user-images.githubusercontent.com/959055/148440337-c819c95d-c4cc-4736-9acf-a1d91b934a6d.png)

**Comment by jagbarcelo** [comment]
El interfaz **eth0** de la RBPi4 tiene habilitado **MULTICAST** y también está suscrita a la dirección **224.0.0.1**:

```
root@pi-u7d:/home/ubuntu# ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e4:5f:01:75:47:38 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.8/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::e65f:1ff:fe75:4738/64 scope link
       valid_lft forever preferred_lft forever
root@pi-u7d:/home/ubuntu# ip maddr show
1:      lo
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
2:      eth0
        link  33:33:00:00:00:01
        link  01:00:5e:00:00:01
        link  01:80:c2:00:00:00
        link  01:80:c2:00:00:03
        link  01:80:c2:00:00:0e
        link  33:33:ff:75:47:38
        inet  224.0.0.1
        inet6 ff02::1:ff75:4738
        inet6 ff02::1 users 2
        inet6 ff01::1
3:      wlan0
        link  33:33:00:00:00:01
        inet6 ff02::1
        inet6 ff01::1
root@pi-u7d:/home/ubuntu#
```

Sin embargo, en el Switch Gigabit al que está conectado (en el puerto 7), no aparece como activo en IGMP Snooping.

![image](https://user-images.githubusercontent.com/6704109/148444096-dab586ec-52c0-4216-af3c-fe1eebb40c38.png)

Por si acaso fuera por esta razón, también he probado a conectarlo directamente al router de Movistar (que tiene sólo 4 puertos) pero el problema persiste.

La cuestión es que tengo otro equipo (otro Ubuntu Server pero en este caso un 20.04 LTS) en el que 
movistar-u7d está funcionando perfectamente. Se trata de una máquina virtual que corre en un NAS Synology, pero estoy tratando de hacer correr todo el proyecto en una RBPi para descargar un poco ese servidor, que anda escaso de RAM. Lo que te quiero quiero decir con esto es que te puedo confirmar que todo funciona en mi red, salvo que no corre cuando lo ejecuto en la RBPi por alguna razón que no logro entender.

**Comment by jagbarcelo** [comment]
Solucionado.

Después de tus cambios sobre [sanic-prometeus](https://github.com/jmarcet/sanic-prometheus), aunque borré el directorio `movistar-u7d`, volví a descargarlo con `git clone... `, volví a copiar los ficheros `.service` sobre `/etc/systemd/system` y los modifiqué de nuevo, etc. Resulta que me faltó un paso:

`cp movistar_u7d.py movistar_epg.py tv_grab_es_movistartv vod.py /usr/local/bin/`

En `/usr/local/bin/` aún estaban los originales del primer intento, antes de haber descargado tus últimos cambios. Ha bastado con copiarlos a su sitio, reiniciar el servicio con `systemctl restart movistar_u7d` y todo ha empezado a funcionar correctamente.

Para tu información, en una Raspberry Pi 4 con 8Gb de RAM, el uso del proxy multicast hace un uso aproximado del 16% de la CPU con 1 stream de video. Muchas gracias por tu ayuda.

**Comment by jagbarcelo** [comment]
Curiosamente, despues de un reinicio de la RBPi4 el problema ha vuelto a aparecer. De nuevo aparece el error 404-Not-Found y se soluciona logueandome en el servidor y simplemente reiniciando el servicio con `systemctl restart movistar_u7d`

¿Es posible que las dependencias para iniciar ese servicio no estén correctamente establecidas y se intente iniciar antes de que haya arrancado la red o alguna otra cosa?

**movistar_u7d.service**
```
[Unit]
Description=Movistar U7D Flussonic TCP Proxy
After=network.target
Requires=movistar_epg.service
```

¿Puede ser que **After=network.target** no sea suficiente y haya que añadir/cambiar algo para que el servicio tarde un poco mas en arrancar?

**Comment by jagbarcelo** [comment]
He seguido haciendo algunas pruebas. Estos son los resultados:

Con tu configuración de dependencias para "movistar_u7d.service":
```
[Unit]
Description=Movistar U7D Flussonic TCP Proxy
After=network.target
```
`movistar_u7d.service` tiene luz verde para lanzarse en cuanto `network.target` está tambien lanzado. En mi caso con la RBPi4, por lo visto no es suficiente porque cualquier llamada posterior a usar el servicio falla si no se reinicia manualmente de nuevo.

Si estudiamos el la cadena crítica para este servicio, vemos que el servicio se inicia sólo 12.392 segundos después del arranque del sistema:
```
root@pi-u7d:/home/ubuntu# systemd-analyze critical-chain movistar_u7d.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

movistar_u7d.service @12.422s
└─network.target @12.392s
  └─wpa_supplicant.service @11.848s +542ms
    └─dbus.service @11.763s
      └─basic.target @11.757s
        └─sockets.target @11.757s
          └─snapd.socket @11.752s +4ms
            └─sysinit.target @11.705s
              └─cloud-init.service @9.331s +2.372s
                └─systemd-networkd-wait-online.service @9.306s +19ms
                  └─systemd-networkd.service @9.165s +114ms
                    └─network-pre.target @9.158s
                      └─cloud-init-local.service @6.147s +3.010s
                        └─boot-firmware.mount @5.813s +36ms
                          └─systemd-fsck@dev-disk-by\x2dlabel-system\x2dboot.service @5.258s +528ms
                            └─local-fs-pre.target @5.175s
                              └─multipathd.service @4.772s +401ms
                                └─systemd-udev-settle.service @2.385s +2.291s
                                  └─systemd-udev-trigger.service @1.408s +944ms
                                    └─systemd-udevd-kernel.socket @1.329s
                                      └─system.slice @895ms
                                        └─-.slice @895ms
root@pi-u7d:/home/ubuntu#
```

Si cambiamos la dependencia de ese servicio para que arranque después de, por ejemplo `user.target`:
```
[Unit]
Description=Movistar U7D Flussonic TCP Proxy
After=multi-user.target
```
entonces tiene que esperar un poco más para que pueda ser lanzado (1min 8seg), pero lo hace de manera consistente y ya no devuelve errores 404. En este caso el la cadena crítica sería esta:
```
root@pi-u7d:/home/ubuntu# systemd-analyze critical-chain movistar_u7d.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

movistar_u7d.service @1min 8.532s
└─multi-user.target @1min 8.493s
  └─getty.target @1min 8.492s
    └─cloud-config.service @1min 6.900s +1.590s
      └─snapd.seeded.service @1min 6.717s +155ms
        └─snapd.service @12.199s +54.496s
          └─basic.target @12.136s
            └─sockets.target @12.135s
              └─snapd.socket @12.129s +5ms
                └─sysinit.target @12.090s
                  └─cloud-init.service @9.737s +2.351s
                    └─systemd-networkd-wait-online.service @9.710s +21ms
                      └─systemd-networkd.service @9.555s +114ms
                        └─network-pre.target @9.548s
                          └─cloud-init-local.service @6.405s +3.142s
                            └─boot-firmware.mount @6.051s +42ms
                              └─systemd-fsck@dev-disk-by\x2dlabel-system\x2dboot.service @5.424s +5>
                                └─local-fs-pre.target @5.344s
                                  └─multipathd.service @4.930s +413ms
                                    └─systemd-udev-settle.service @2.431s +2.400s
                                      └─systemd-udev-trigger.service @1.531s +894ms
                                        └─systemd-udevd-kernel.socket @1.449s
                                          └─system.slice @987ms
                                            └─-.slice @987ms
root@pi-u7d:/home/ubuntu#
```

Usar esta dependencia tan tardía tal vez pueda ser excesiva, pero puesto que no se trata de un servicio crítico y los reinicios pueden darse con relativa poca frecuencia, creo que sería útil hacer el arranque del servicio más robusto a costa de que pueda tardar un poquito más en estar disponible.

Saludos.

**Comment by jmarcet** [comment]
> ¿Puede ser que **After=network.target** no sea suficiente y haya que añadir/cambiar algo para que el servicio tarde un poco mas en arrancar?

Sí, perfectamente. Los systemd es lo que menos he probado.

**Comment by jmarcet** [comment]
Interesante.

Me surgen dos dudas. La primera es si el otro servicio no se ve afectado en lo más mínimo, es decir, funciona correctamente tal como está, con `After=network.target` y la segunda es si en lugar de `After=multi-user.target`, no sería suficiente con `After=sockets.target`

**Comment by jagbarcelo** [comment]
El otro servicio `movistar_epg.service` no parece dar ningún problema tal y como está (con `After=network.target`). Si fallara en la primera ejecución, como repite periódicamente la descarga de la guía, lo terminaría haciendo bien las veces siguientes. Lo miro de todos en el próxima ocasión que tenga. También miraré si con `After=sockets.target` es suficiente para que funcione bien `movistar_u7d.service`

**Comment by jmarcet** [comment]
Si me confirmas que funciona bien lo dejaré así:

```
diff --git a/movistar_epg.service b/movistar_epg.service
index e5b8cc6..07a02e9 100644
--- a/movistar_epg.service
+++ b/movistar_epg.service
@@ -1,6 +1,6 @@
 [Unit]
 Description=Movistar U7D - EPG State service
-After=network.target
+After=network.target sockets.service

 [Service]
 Type=simple
diff --git a/movistar_u7d.service b/movistar_u7d.service
index f262bff..66aa94f 100644
--- a/movistar_u7d.service
+++ b/movistar_u7d.service
@@ -1,6 +1,6 @@
 [Unit]
 Description=Movistar U7D Flussonic TCP Proxy
-After=network.target
+After=network.target sockets.service
 Requires=movistar_epg.service

 [Service]
```

**Comment by jagbarcelo** [comment]
Sí, pero no...

Esos cambios sobre una Raspberry Pi 2 B+ (modelo de 2014 con 1Gb de RAM), con Ubuntu Server 20.10 de 32bits, arranca y funciona perfectamente. La cadena crítica sería:

```
root@pi-u7d:/home/ubuntu# systemd-analyze critical-chain movistar_u7d.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

movistar_u7d.service @32.292s
└─network.target @32.206s
  └─wpa_supplicant.service @31.533s +668ms
    └─dbus.service @31.296s
      └─basic.target @31.281s
        └─sockets.target @31.278s
          └─snapd.socket @31.266s +10ms
            └─sysinit.target @31.160s
              └─cloud-init.service @24.615s +6.539s
                └─systemd-networkd-wait-online.service @24.464s +110ms
                  └─systemd-networkd.service @24.073s +356ms
                    └─network-pre.target @24.054s
                      └─cloud-init-local.service @16.719s +7.332s
                        └─boot-firmware.mount @14.545s +2.079s
                          └─systemd-fsck@dev-disk-by\x2dlabel-system\x2dboot.service @13.492s +1.01>
                            └─local-fs-pre.target @13.319s
                              └─multipathd.service @12.420s +896ms
                                └─systemd-udev-settle.service @4.880s +6.394s
                                  └─systemd-udev-trigger.service @2.757s +2.073s
                                    └─systemd-udevd-kernel.socket @2.537s
                                      └─system.slice @1.491s
                                        └─-.slice @1.491s
```

Como información útil (por si a alguien le interesa), cuando se está reproduciendo un canal (1 stream) el uso de CPU (top) se estabiliza en torno al 35%:

```
top - 00:33:04 up 11 min,  1 user,  load average: 0.15, 0.31, 0.33
Tasks: 139 total,   1 running, 138 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.0 us,  3.8 sy,  0.0 ni, 91.1 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :    917.5 total,    440.9 free,    224.0 used,    252.6 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    672.0 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 1774 root      20   0   35484  25140   5588 S  34.4   2.7   0:42.75 movistar_u7d
 2074 root      20   0    9484   2856   2300 R   1.6   0.3   0:03.90 top
   12 root      20   0       0      0      0 S   0.3   0.0   0:00.79 ksoftirqd/0
 1569 root      20   0       0      0      0 I   0.3   0.0   0:00.98 kworker/0:5-events
 2077 root      20   0       0      0      0 I   0.3   0.0   0:00.07 kworker/2:0-events
    1 root      20   0   31524   8184   5588 S   0.0   0.9   0:16.45 systemd
    2 root      20   0       0      0      0 S   0.0   0.0   0:00.03 kthreadd
[...]
```

Sin embargo, si repetimos esos cambios en una Raspberry Pi 4 (con 8Gb de RAM) y Ubuntu Server 20.10 de 64bits, después del arranque vuelve a sacar mensajes 404-not-found. En este caso la cadena crítica sería:

```
root@pi-u7d:/home/ubuntu# systemd-analyze critical-chain movistar_u7d.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

movistar_u7d.service @12.104s
└─network.target @12.063s
  └─wpa_supplicant.service @11.484s +577ms
    └─dbus.service @11.399s
      └─basic.target @11.392s
        └─sockets.target @11.391s
          └─snapd.socket @11.386s +4ms
            └─sysinit.target @11.350s
              └─cloud-init.service @9.019s +2.329s
                └─systemd-networkd-wait-online.service @8.994s +19ms
                  └─systemd-networkd.service @8.854s +114ms
                    └─network-pre.target @8.846s
                      └─cloud-init-local.service @5.903s +2.942s
                        └─boot-firmware.mount @5.669s +32ms
                          └─systemd-fsck@dev-disk-by\x2dlabel-system\x2dboot.service @5.186s +452ms
                            └─local-fs-pre.target @5.106s
                              └─multipathd.service @4.706s +399ms
                                └─systemd-udev-settle.service @2.392s +2.253s
                                  └─systemd-udev-trigger.service @1.425s +937ms
                                    └─systemd-udevd-kernel.socket @1.342s
                                      └─system.slice @907ms
                                        └─-.slice @907ms
root@pi-u7d:/home/ubuntu#
```

El árbol tiene exactamente las mismas ramas, pero el tiempo de ejecución de cada una cambia (la placa más moderna es más rápida, lógicamente). Aparte de los tiempos, no entiendo porqué en la Pi2 (la más vieja y lenta) sí funciona bien pero no lo hace en la Pi4 (más nueva y rápida).

Después de reiniciar el servicio con `systemctl start movistar_u7d`, el stream de 1 canal funciona perfectamente y el uso de CPU se estabiliza en torno al 17%:

```
top - 00:58:06 up 15 min,  1 user,  load average: 0.07, 0.05, 0.07
Tasks: 150 total,   2 running, 148 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.2 us,  2.2 sy,  0.0 ni, 95.4 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   7809.5 total,   7112.0 free,    336.7 used,    360.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   7217.5 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   2146 root      20   0   53760  38248   6940 R  16.8   0.5   0:10.74 movistar_u7d
   2147 root      20   0   11776   3368   2744 R   0.7   0.0   0:00.55 top
   2126 root      20   0       0      0      0 I   0.3   0.0   0:00.47 kworker/1:0-events
      1 root      20   0  165388  11020   7252 S   0.0   0.1   0:10.96 systemd
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.02 kthreadd
[...]
```

Mañana probaré en las 2 RBPi de las que dispongo, con configuraciones que esperen hasta que haya iniciado `cloud-config.service` y te cuento.

**Comment by jmarcet** [comment]
Hmm, bastante curioso todo, tanto las dependencias como los datos de consumo. Si te digo la verdad sólo he hecho pruebas con placas parecidas a las raspberries pero no raspberries directamente.

Tampoco soy excesivamente amigo de distros que usen glibc para placas de este estilo, por eso tiendo a usar OpenWRT y hacer builds propios, con musl. Dicho esto, me pregunto si notarías diferencias de rendimiento de esa manera. Las imágenes de docker que comparto están hechas sobre alpine, que también usa musl en lugar de glibc, y reduce de forma bastante importante todos los tamaños de ejecutables. No estoy seguro si el rendimiento mejoraría, pero sí me queda la curiosidad.

Aparte de eso, si me confirmas alguna forma de dependencias concretas que aseguren el arranque correcto en ambas placas, actualizo los systemd.

**Comment by jagbarcelo** [comment]
Para simplificar las pruebas, he empezado primero con la RBPi4 y como el servicio `movistar_epg.service` no ha dado problemas en ningún momento, lo he dejado sin cambios respecto del original (`After=network.target`)

A partir de ahí, he probado diferentes alternativas para `After=`, intentando usar algo de lógica en los sucesivos cambios para el  **Movistar U7D Flussonic TCP Proxy** `movistar_u7d.service`:
* Como es posible que haga uso de los servicios de fecha/hora: `systemd-timedated.service`
* Como el servidor DNS de movistar debe estar disponible: `nss-lookup.target`
* Tambien he ido subiendo en la cadena crítica inicial, hasta llegar a `getty.target` (que tampoco funcionaba).
* Combinaciones de los anteriores (varias entradas separadas con espacio)

Al final he tenido que llegar hasta `multi-user.target` que es con lo único que parece funcionar, pero tampoco me convence eso sin ninguna razón que lo justifique (tal vez en otro escenario/condiciones tampoco sea suficiente).

Entonces he revisado uno de tus comentarios:


> Yo personalmente lo uso dentro de un docker desde OpenWRT. Si te fijas el docker usa un [script de inicio](../blob/master/start.sh) que antes de lanzar el primer daemon, `movistar_epg.py`, [comprueba que las dns de movistar sean accesibles](../blob/2bbf89a5a4edc592d2a5a2588ee76a76d7fa5611/start.sh#L9), y antes de lanzar `movistar_u7d.py` [comprueba que movistar_epg.py esté ya escuchando peticiones](../blob/2bbf89a5a4edc592d2a5a2588ee76a76d7fa5611/start.sh#L11).

Y he modificado los `.service` para hacer exactamente lo mismo que haces en Docker:

---
**movistar_epg.service**
```
[Unit]
Description=Movistar U7D - EPG State service
After=network.target

[Service]
Type=simple
# Environment=HOME=/home
# Environment=LAN_IP=192.168.1.10
# Environment=EPG_THREADS=4
# Environment=RECORDING_THREADS=4
# Environment=RECORDINGS=/mnt/recordings
# Environment=SANIC_PORT=8888
# Environment=U7D_UID=nobody

# Antes de lanzar movistar_epg.py, comprueba que las dns de movistar sean accesibles
ExecStartPre=/bin/bash -c 'while (true); do nc -z -v -w 1 172.26.23.3 53 2>/dev/null && break; sleep 1; done'
ExecStart=movistar_epg.py

[Install]
WantedBy=multi-user.target
```

---
**movistar_u7d.service**
```
[Unit]
Description=Movistar U7D Flussonic TCP Proxy
After=network.target
Requires=movistar_epg.service

[Service]
Type=simple
# Environment=HOME=/home
# Environment=LAN_IP=192.168.1.10
# Environment=IPTV_BW=85000
# Environment=RECORDINGS=/mnt/recordings
# Environment=SANIC_PORT=8888
# Environment=SANIC_THREADS=4
# Environment=U7D_UID=nobody

# Antes de lanzar movistar_u7d.py, comprueba que movistar_epg.py esté ya escuchando peticiones
ExecStartPre=/bin/bash -c 'while (true); do nc -z -v -w 1 127.0.0.1 8889 2>/dev/null && break; sleep 1; done'
ExecStart=movistar_u7d.py

[Install]
WantedBy=multi-user.target
```

La clave son las líneas [`ExecStartPre`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=)

Con estos cambios no tenemos en cuenta ningún tipo de dependencias entre servicios y el sistema se comporta exactamente igual tanto si se instala a través de Docker o manualmente como en este caso.

Funciona bien y verificado tras varios reinicios tanto en la RBPi4 como la RBPi2.

**Comment by jmarcet** [comment]
Vale, gracias por todas las pruebas.

En principio sólo lo vi necesario al ejecutarse en el propio router, donde es variable el tiempo exacto que tarda la VLAN de iptv en estar disponible. Para otros dispositivos pensé que sería suficiente que la red estuviera activa.

Pero me parece bien, me gusta más que la opción de `After=multi-user.target`.

Lo dejo tal como lo has puesto arriba 😄
