### ISSUE TITLE
version.py requerida pero ausente en las instrucciones para Linux/UNIX/OS X

### ISSUE THREAD

**Issue by jagbarcelo** [jmarcet/movistar-u7d#17]
Buenos días,

Acabo de actualizar mi instalación (en Raspberry PI) a partir de los cambios que subiste ayer. Al intentar ejecutar de nuevo los servicios me saltan las siguientes advertencias y error al final:

```
root@pi-u7d:/usr/local/bin# movistar_u7d.py
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/usr/local/bin/movistar_u7d.py", line 27, in <module>
    from movistar_epg import get_ffmpeg_procs
  File "/usr/local/bin/movistar_epg.py", line 26, in <module>
    from version import _version
ModuleNotFoundError: No module named 'version'
root@pi-u7d:/usr/local/bin#
```

Por lo visto el nuevo fichero [version.py ](https://github.com/jmarcet/movistar-u7d/blob/master/version.py) también es necesario en el directorio donde están el resto de ficheros, /usr/local/bin/ según tus instrucciones para [Instalación en Linux/UNIX/OS X](https://github.com/jmarcet/movistar-u7d#instalaci%C3%B3n-en-linuxunixos-x).

Actualmente indicas:
`cp movistar_u7d.py movistar_epg.py tv_grab_es_movistartv vod.py /usr/local/bin/`

Actualiza la línea para que también se copie **version.py**
`cp movistar_u7d.py movistar_epg.py tv_grab_es_movistartv vod.py version.py /usr/local/bin/`

Copiando ese fichero y ejecutando de nuevo **pip3 install -r requirements.txt** vuelve a funcionar todo.

Quedan pendientes esas advertencias sobre la conveniencia de usar el módulo **importlib** en lugar de **imp**.

Saludos.

**Comment by jmarcet** [comment]
Gracias por avisar! Se me escapó actualizar el README, tienes toda la razón.

En cuanto a la advertencia, no la había visto antes, desde luego ni en Arch linux ni en docker con las imágenes de Alpine la he visto. ¿Has buscado algo más al respecto?
