### ISSUE TITLE
channels.m3u no incluye a "La1 HD"

### ISSUE THREAD

**Issue by jagbarcelo** [jmarcet/movistar-u7d#19]
El fichero de canales generado no incluye "La1 HD" (id de canal 2543).

Si modifico `tv_grab_es_movistartv` y añado:
`    "2543",`
al array `epg_channels`, se añade a la lista de canales y se puede ver perfectamente.

https://github.com/jmarcet/movistar-u7d/blob/320254ffec03b5f30a23bdeefcd737dc6d77e915/tv_grab_es_movistartv#L48

Tal vez en algunas regiones haya cambiado de número. En Murcia sigue siendo el 2543 y aún está activo.

**Comment by jmarcet** [comment]
Vaya, ¿de verdad no ha cambiado y sólo ha pasado aquí? Qué curioso.

Pues lo añado de vuelta, no me imaginé esta posibilidad.

**Comment by jmarcet** [comment]
Gracias por avisar, de esto sí que no me podía enterar yo sin moverme de comunidad 😄

**Comment by jagbarcelo** [comment]
Comprobado ahora mismo. Sigo recibiendo en abierto La 1 HD en el número 2543.

**Comment by jmarcet** [comment]
Curioso, aquí ha pasado a estar encriptado, con el 5066, el miércoles durante la emisión de `Dios mío, ¿pero qué te hemos hecho... ahora?`

![image](https://user-images.githubusercontent.com/959055/153710736-907b4b86-0735-4769-ac78-e18f0ffb85f4.png)

![image](https://user-images.githubusercontent.com/959055/153710746-5fc4cdee-1f35-47fe-bf67-ee69686da2ff.png)

Por curiosidad, ¿qué tipo de subscripción tienes? Me llaman mucho la atención tanto el cambio de id como ahora el encriptado, y que no te afecten ninguno. Yo tengo `Conecta Max TV Box`.

**Comment by jmarcet** [comment]
El identificador `2543` no me aparece en todos los metadatos de Movistar, así que en Galicia ha dejado de usarse, da igual el tipo de abono.

**Comment by jagbarcelo** [comment]
No se exactamente el nombre. Lo tengo desde hace años (tal vez 8 o 10) y es posible que ahora no exista con ese nombre. Es un paquete Fusión que incluye series y 600Mbps simétricos (de la época en la que lo habitual eran 100Mbps). Ahora 1Gbps.

**Comment by jmarcet** [comment]
Pues suerte que te dura en abierto, ojalá no te lo empeoren.
