### ISSUE TITLE
No encuentra el archivo epg.json

### ISSUE THREAD

**Issue by jesusvpct** [jmarcet/movistar-u7d#2]
Buenas, lo primero dar las gracias por este aporte que aunque como bien dices, al final acabará todo con DRM, mientras se pueda, aprovecharemos lo que dure.

Lo segundo, he instalado las dependencias con pip3, y al ejecutar el script movistar_epg.py, me sale el siguiente error:
````
./movistar_epg.py 
[2021-08-24 13:58:16] [17987] [INFO] Goin' Fast @ http://127.0.0.1:8889
[2021-08-24 13:58:16] [17987] [ERROR] Failed to load EPG data [Errno 2] No such file or directory: '/home/jesus/.xmltv/cache/epg.json'
[2021-08-24 13:58:16] [17987] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/jesus/.local/lib/python3.8/site-packages/sanic/app.py", line 1052, in run
    serve_single(server_settings)
  File "/home/jesus/.local/lib/python3.8/site-packages/sanic/server.py", line 749, in serve_single
    serve(**server_settings)
  File "/home/jesus/.local/lib/python3.8/site-packages/sanic/server.py", line 599, in serve
    loop.run_until_complete(app._server_event("init", "after"))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/jesus/.local/lib/python3.8/site-packages/sanic/app.py", line 1495, in _server_event
    await self.dispatch(
  File "/home/jesus/.local/lib/python3.8/site-packages/sanic/signals.py", line 163, in dispatch
    return await dispatch
  File "/home/jesus/.local/lib/python3.8/site-packages/sanic/signals.py", line 133, in _dispatch
    retval = await maybe_coroutine
  File "/home/jesus/.local/lib/python3.8/site-packages/sanic/app.py", line 1382, in _listener
    await maybe_coro
  File "./movistar_epg.py", line 59, in after_server_start
    await reload_epg()
  File "./movistar_epg.py", line 242, in reload_epg
    async with await open_async(epg_data) as f:
  File "/home/jesus/.local/lib/python3.8/site-packages/aiofiles/base.py", line 75, in __aenter__
    self._obj = await self._coro
  File "/home/jesus/.local/lib/python3.8/site-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jesus/.xmltv/cache/epg.json'
[2021-08-24 13:58:16] [17987] [CRITICAL] [Errno 2] No such file or directory: '/home/jesus/.xmltv/cache/epg.json'
````

No sé si es que hay algo que me falta, pero parece que no encuentra el archivo en un directorio propio del home, que efectivamente, ni existe.

¿Qué me falta por hacer?

Gracias.

**Comment by jmarcet** [comment]
Hola @jesusvpct,

Gracias por avisar. Era un bug que se coló hace unas semanas. Sucedía al usarlo por primera vez o tras haber borrado la epg del disco.

Acabo de arreglarlo, de paso lo he hecho más resistente a problemas cargando la EPG.

Actualiza tu repo, prueba de nuevo y me dices :)

Las imágenes de docker estarán en un rato, están en [construcción](https://gitlab.marcet.info/javier/movistar-u7d/-/jobs/805)

**Comment by jesusvpct** [comment]
Gracias. Acabo de probarlo, lo mismo en mi comunidad está capado, porque mira lo que me sale en el log:
```
2021-08-29 13:00:46] [INFO] ---------------------------------------------------
[2021-08-29 13:00:46] [INFO] MovistarTV EPG Grabber
[2021-08-29 13:00:46] [INFO] Parámetros: ['--tvheadend', '/home/jesus/MovistarTV.m3u', '--output', '/home/jesus/guide.xml']
[2021-08-29 13:00:46] [INFO] ---------------------------------------------------
[2021-08-29 13:00:46] [INFO] Cookie: JSESSIONID=453E01026A8BF50C51C621A0D51E58EF-node8; Path=/appserver; HttpOnly
[2021-08-29 13:00:46] [INFO] tvPackages: UTXC8|UTXH5|UTY4Q|UTY4R
[2021-08-29 13:00:46] [INFO] Demarcation: 12
[2021-08-29 13:00:46] [INFO] Buscando el Proveedor de Servicios de Murcia
[2021-08-29 13:00:46] [DEBUG] Caché: datos del Proveedor de Servicios no encontrados
[2021-08-29 13:00:46] [DEBUG] Descargando XML de 239.0.2.129:3937
[2021-08-29 13:00:49] [ERROR] Error al descargar los archivos XML: timed out
[2021-08-29 13:00:49] [ERROR] Usando el Proveedor de Servicios por defecto: 239.0.2.150
[2021-08-29 13:00:49] [DEBUG] Descargando XML de 239.0.2.150:3937
[2021-08-29 13:00:52] [ERROR] Error al descargar los archivos XML: timed out
[2021-08-29 13:00:52] [CRITICAL] timed out
```
Un saludo.

**Comment by jmarcet** [comment]
Hmm, no le llega el multicast de movistar.

No entiendo eso de tu comunidad. Esto sólo funciona con una línea de fibra de Movistar con canales de TDT.

Tienes deco de Movistar? Te funciona?

**Comment by jesusvpct** [comment]
Tengo un router y luego 2 decodificadores, Uno para el salón y el otro para la cocina. Ambos funcionan bien.

Me refería que lo mismo en la Región de Murcia tienen capado algo para que no se pueda (es por decir algo).

Un saludo.

**Comment by jmarcet** [comment]
Y lo conectas todo al router de Movistar directamente? Tiene que ser todo por cable para que le llegue bien el tráfico multicast iptv.

No tendrás algún switch intermedio que esté cortando dicho tráfico o algo similar?

**Comment by jesusvpct** [comment]
Sí, los dos decodificadores están conectados por RJ-45 al igual que mi ordenador, todo conectado directamente al router.

Un saludo.

**Comment by jmarcet** [comment]
Pues no se me ocurre nada más. Funcionando los decos originales, esto debería funcionar también.

Recuerdo que mientras lo desarrollaba, si tenía funcionando el addon del kodi, hacía que la carga de la epg fuera mucho más lenta. Te diría que probases a ejecutarlo una vez con los otros decos desenchufados del router, como para que sólo le llegue al proxy el tráfico multicast, pero se me hace raro igualmente, una cosa es que tarde más y otra que no le llegue nada.

Todo pasa porque te funcione el grabber de EPG, que tiene su [origen aquí](https://github.com/MovistarTV/tv_grab_es_movistartv). En [este hilo](https://www.adslzone.net/foro/movistar-tv-imagenio.38/obtener-lista-canales-programacion-movistar-tv.359916) hay mucha más información.

**Comment by jesusvpct** [comment]
¿Puede ser que hayan cambiado algo? Lo que tengo de Movistar es relativamente nuevo, de hace unos meses.

**Comment by jesusvpct** [comment]
En la configuración avanzada del route he visto esto en la sección Multicast:

```
Index | Group Address | Interface(s)
-- | -- | --
0 | 239.0.2.2 | ip4,eth0.4,eth0.1
1 | 239.0.2.29 | ip4,eth0.4,eth0.1
2 | 239.0.2.149 | eth0.1,eth0.4,ip4
3 | 239.0.2.129 | eth0.1,eth0.4,ip4
4 | 239.0.0.87 | eth0.1,ip4,eth0.4
```

**Comment by jmarcet** [comment]
No, no lo creo. Piensa que todos los decos han seguido funcionando sin cambios.

Como te dije antes, todo pasa por hacer funcionar el grabber de la EPG. En su [README](https://github.com/MovistarTV/tv_grab_es_movistartv/blob/master/README.md) comenta al final:

```
- Error al descargar los archivos XML: timed out
La descarga de la guía básica que viene por Multicast es multihilo, se conecta a varias IP simultáneamente para agilizar el tiempo de ejecución del grabber. Por defecto hay tres hilos (tres conexiones a tres IP diferentes) porque a partir de cuatro he notado que pueden aparecer errores de este tipo.

Si es tu caso, baja el número de conexiones a dos: edita el grabber, busca la línea threads = 3 y cámbiala por threads = 2.

Si sigues teniendo problemas desactiva el multihilo: busca la línea use_multithread = True y cámbiala por use_multithread = False
```

Eso sería [aquí](https://github.com/jmarcet/movistar-u7d/blob/e86c17c612900ffae8fbda77d070359318b9b477/tv_grab_es_movistartv#L797) para bajar los hilos (a 8 por defecto), y [aquí](https://github.com/jmarcet/movistar-u7d/blob/e86c17c612900ffae8fbda77d070359318b9b477/tv_grab_es_movistartv#L90) para desactivar el multihilo, cambiándolo a `False`.

Me olvido que yo lo uso con mi propio router x86, mucho más potente que el router de movistar, hace tiempo que no pruebo todo con el router original.

Puedes probar a ver si cambiando alguno de esos valores te funciona?

A parte de eso, ¿En qué tipo de máquina lo haces funcionar? ¿Un ordenador normal o algo más pequeño tipo raspberry?

**Comment by jmarcet** [comment]
> En la configuración avanzada del route he visto esto en la sección Multicast:
> 
> ```
> Index | Group Address | Interface(s)
> -- | -- | --
> 0 | 239.0.2.2 | ip4,eth0.4,eth0.1
> 1 | 239.0.2.29 | ip4,eth0.4,eth0.1
> 2 | 239.0.2.149 | eth0.1,eth0.4,ip4
> 3 | 239.0.2.129 | eth0.1,eth0.4,ip4
> 4 | 239.0.0.87 | eth0.1,ip4,eth0.4
> ```

Y esos eth0.1,  y eth0.4 qué son, los puertos del router? ¿Serían entonces los otros dos decos? Y el puerto al que está conectado el aparato donde ejecutas este proxy, cuál sería? No le llega nunca tráfico multicast?

**Comment by jesusvpct** [comment]
Estoy usando mi torre, un AMD RYZEN 3950X.

He puesto 2 threads y False en use_multithread, pero sigue pasando lo mismo.

Sobre la configuración, no lo sé, es lo que viene en la parte de configuración del Router, te puedo mandar una captura, si te soy sincero, no sé qué significa.

Un saludo.

![imagen](https://user-images.githubusercontent.com/5315258/131251772-76aad584-1354-4f72-80eb-e611ec04c4bb.png)
![imagen](https://user-images.githubusercontent.com/5315258/131251789-3bb3feb0-dafe-4d0f-b033-975bdf76b06b.png)
![imagen](https://user-images.githubusercontent.com/5315258/131251813-2856cfde-b0f4-4aad-ba5d-f2d36cb21fce.png)
![imagen](https://user-images.githubusercontent.com/5315258/131251829-09e2fb6a-ceda-42fa-a43c-af31a06b3276.png)
![imagen](https://user-images.githubusercontent.com/5315258/131251840-bf5fabd4-9fb6-45f7-b7bc-f69e8e48d45c.png)

**Comment by jmarcet** [comment]
Hmmm, creo que ya sé qué es.

En la primera foto de todas, donde sale el IGMP sólo activo para `ip4`, pero no para `ip3` ni para `ip2`. Si, como me parece, eso son los puertos del router, necesitas activarlo también para el puerto donde esté tu ordenador. Prueba a poner `ip2` e `ip3` igual que está `ip4`, `Enabled` y con `IGMPv2`.

**Comment by jesusvpct** [comment]
Hecho, pero sigue pasando lo mismo.

Un saludo.

**Comment by jmarcet** [comment]
Pues no entiendo.

En el ordenador qué IP tienes? O mejor dicho, qué IP ve el proxy? Donde ejecutas el software? En un linux directamente o cómo?

**Comment by jmarcet** [comment]
Es imprescindible que el software tenga acceso a la LAN normal del router de Movistar. Eso quiere decir que no puede haber ningún tipo de virtualización o emulación en la red, de ahí que recomiende usar Docker con la red en modo host.

El rango por defecto para la LAN de los routers de Movistar es `192.168.1.1 - 192.168.1.255`. Sólo en ese rango funciona el multicast, por lo que el proxy debe tener una IP dentro del mismo.

**Comment by jesusvpct** [comment]
Estoy conectado directamente al router con el ordenador, estoy usando KDE Neon (basado en Ubuntu 20.04), no está virtualizado.

La IP de mi máquina está dentro del rango, es 192.168.1.43, aunque también veo que tiene una IPv6 fe80::a59f:3e29:a554:9d5f

No sé si puede estar interfiriendo en algo.

Un saludo.

**Comment by jmarcet** [comment]
Pues no entiendo nada.

Algo relacionado con el IGMP casi seguro.

Desenchufar los otros dos routers mientras pruebas ya lo has probado, no? Y además de eso, enchufar el ordenador en el mismo puerto donde funciona alguno de los decos?

**Comment by jesusvpct** [comment]
Lo que también veo es que hay dos LAN, una con los ordenadores, y otra con los decodificadores:

Una va de la 192.168.1.33 a la 192.168.1.199 (la de ordenadores, móviles, etc) y la otra va de la 192.168.1.200 a la 192.168.1.223 (que es la de los dos decodificadores)

Quizá eso tenga algo que ver...

Un saludo.

**Comment by jmarcet** [comment]
Hmm, sí, la segunda lan cambia la dns fundamentalmente.

Si ejecutas:

```
dig @172.26.23.3 telefonica.net
```

Eso resuelve el dominio `telefonica.net` usando el servidor de dns de la vlan de iptv de movistar. Tienes acceso a él? Si lo añades al `/etc/resolv.conf` cambia algo?

**Comment by jmarcet** [comment]
Necesitas conseguir que el IGMP funcione en el puerto donde está el ordenador y que por tanto le llegue el tráfico multicast, y necesitas también acceso a las dns originales de movistar. Con dnsmasq en linux, necesitarías esto en la configuración:

```
server=/telefonica.net/172.26.23.3
```

En [este hilo](https://www.adslzone.net/foro/movistar-tv-imagenio.38/obtener-lista-canales-programacion-movistar-tv.359916/page-10) tienes mucha más información.

Me interesa mucho saber cuál es el problema si consigues arreglarlo.

**Comment by jesusvpct** [comment]
> Hmm, sí, la segunda lan cambia la dns fundamentalmente.
> 
> Si ejecutas:
> 
> ```
> dig @172.26.23.3 telefonica.net
> ```
> 
> Eso resuelve el dominio `telefonica.net` usando el servidor de dns de la vlan de iptv de movistar. Tienes acceso a él? Si lo añades al `/etc/resolv.conf` cambia algo?

Sí, tengo acceso, y me devuelve un resultado.

Lo he metido en resolv.conf y tampoco va.

Echaré un vistazo al hilo que mencionas, a ver si veo algo que me ayude.

Gracias.

**Comment by jmarcet** [comment]
Si encuentras cómo solucionarlo, coméntalo por favor.

**Comment by jesusvpct** [comment]
Sí, claro, aunque de momento poco sé qué hacer jeje, pero lo intentaré.

**Comment by jmarcet** [comment]
Has probado lo que te dije de conectar el ordenador al mismo puerto donde tengas alguno de los decos?

El problema está ahí, algo le falta a la lan principal.

**Comment by jesusvpct** [comment]
¿Te refieres a que cambie el cable de puerto? No, no lo he probado. Tan sólo he puesto una IP del rango de 200-223 para estar igual que los decos (puedo hacerles ping) y he metido la DNS 172.26.23.3 (aunque creo que esto usando las DNS de Movistar no es necesario). Y de momento sin éxito.

**Comment by jmarcet** [comment]
Pues sí, me refería a que cambiases el cable de puerto. Prueba sólo con el ordenador conectado al router y en uno de los puertos donde tienes uno de los decos.

No pretendo que dejes de usar los decos, es sólo para probar.

**Comment by jesusvpct** [comment]
Acabo de hacer el cambio en el router, me he puesto mi ordenador en el de uno de los decos, pero tampoco va.

**Comment by jmarcet** [comment]
Pues algo tienes raro en el router. Has cambiado algún ajuste en él con respecto a como te lo instalan?

**Comment by jesusvpct** [comment]
Qué va! No había accedido aún al router hasta hoy, para ver si había algo que pudieras ver que fuese el problema.

**Comment by jmarcet** [comment]
:'(

Mirate el hilo que te dije, entero, tiene mucha chicha y hablan precisamente del problema que tienes.

A mí me supone un engorro enorme enchufar el router original.

Si se me ocurre algo más, te comento, pero ya es pelearse con el router hasta que tengas acceso a esas direcciones 239.xxx desde el ordenador.

**Comment by jesusvpct** [comment]
Tranquilo, en eso estoy, mirando a ver si veo algo en el hilo.

Gracias!

**Comment by jesusvpct** [comment]
Buenas, aún sigo sin que funcione, peeeero, tengo una buena noticia (o eso creo). En una web venía un ejemplo de ver TVE1, que es con VLAN y reproduciendo rtp://@239.0.0.76:8208 y eso me funciona. Es decir, parece que tengo conexión con Multicast correctamente, ¿no?

**Comment by jmarcet** [comment]
Hola @jesusvpct,

Pues sí, eso indica que en principio sí que tienes acceso al multicast. Pero más extrañado me quedo, las DNS van bien, el multicast también, pero la EPG da timeouts.

Puedes probar a ejecutar todo con las variables de entorno `IPTV_ADDRESS` y `LAN_IP` ambas con la ip de la lan del ordenador?

**Comment by jesusvpct** [comment]
Perdona, pero cuando dices la IP de la LAN del ordenador, ¿es la IP que tengo asignada o cualquiera que no esté usada?

**Comment by jesusvpct** [comment]
He puesto mi IP en ambas variables, y ahora intenta descargarlo (hemos progresado) pero falla con otro error:
```
[2021-08-30 12:45:54] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[2021-08-30 12:45:54] [DEBUG] Descargando XML de 239.0.2.148:3937
[2021-08-30 12:46:25] [INFO] Ficheros XML descargados: [2_0 5_0 6_0] / [2_0 5_0 6_0]
[2021-08-30 12:46:25] [DEBUG] Caché: metadatos de la EPG no encontrados
[2021-08-30 12:46:25] [CRITICAL] 'NoneType' object is not subscriptable
```

**Comment by jesusvpct** [comment]
Lo dejo ejecutándose, pero da ese fallo continuamente en cada intento que hace.

**Comment by jmarcet** [comment]
Gracias por insistir :smile: [arreglo](https://github.com/jmarcet/movistar-u7d/commit/b42b932cbb130e608c15e0ef365fb1acaa5b6057)

Actualiza y prueba de nuevo, había un bug estúpido, por tratar de loggear un dato que no existía.

Muchísimas gracias por la insistencia :smiley:

**Comment by jesusvpct** [comment]
Me alegra que hayas podido encontrar un bug. He descargado los cambios y lo estoy ejecutando, pero de momento el resultado es el mismo. He cambiado los threads a 2 por si eso mejora, pero de momento tampoco.

Si hay algo más que se te ocurra que pueda hacer, lo hago.

Un saludo.

**Comment by jmarcet** [comment]
Espera, el resultado que pegaste antes:

```
[2021-08-30 12:45:54] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[2021-08-30 12:45:54] [DEBUG] Descargando XML de 239.0.2.148:3937
[2021-08-30 12:46:25] [INFO] Ficheros XML descargados: [2_0 5_0 6_0] / [2_0 5_0 6_0]
[2021-08-30 12:46:25] [DEBUG] Caché: metadatos de la EPG no encontrados
[2021-08-30 12:46:25] [CRITICAL] 'NoneType' object is not subscriptable
```

Qué más habías hecho para obtener ese resultado? Ese bug está arreglado.

Qué error te da ahora?

**Comment by jesusvpct** [comment]
Pues de momento el mismo
```
[2021-08-30 18:45:15] [INFO] ---------------------------------------------------
[2021-08-30 18:45:15] [INFO] MovistarTV EPG Grabber
[2021-08-30 18:45:15] [INFO] Parámetros: ['--tvheadend', '/home/jesus/MovistarTV.m3u', '--output', '/home/jesus/guide.xml']
[2021-08-30 18:45:15] [INFO] ---------------------------------------------------
[2021-08-30 18:45:15] [INFO] Cookie: JSESSIONID=06CF32E093F6C07CE673D2934F327C63-node5; Path=/appserver; HttpOnly
[2021-08-30 18:45:15] [INFO] tvPackages: UTXC8|UTXH5|UTY4Q|UTY4R
[2021-08-30 18:45:15] [INFO] Demarcation: 12
[2021-08-30 18:45:15] [INFO] Buscando el Proveedor de Servicios de Murcia
[2021-08-30 18:45:15] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[2021-08-30 18:45:15] [DEBUG] Descargando XML de 239.0.2.148:3937
[2021-08-30 18:46:00] [INFO] Ficheros XML descargados: [2_0 5_0 6_0] / [2_0 5_0 6_0]
[2021-08-30 18:46:00] [DEBUG] Caché: metadatos de la EPG no encontrados
[2021-08-30 18:46:00] [CRITICAL] 'NoneType' object is not subscriptable
```

Lo que hice para que empezara a hacer la petición fue poner las variables de entorno IPTV_ADDRESS y LAN_IP a la IP de mi ordenador.

**Comment by jmarcet** [comment]
Vuelve a actualizar. 

Puedes probar directamente:
```
/app/tv_grab_es_movistartv --tvheadend /home/jesus/MovistarTV.m3u --output /home/jesus/guide.xml
```

Que es lo que queremos que funcione.

**Comment by jmarcet** [comment]
Ahora si no usas las variables de entorno da de nuevo los timeouts o pasa lo que te está pasando ahora?

**Comment by jesusvpct** [comment]
Ahora funciona! Aunque está tardando lo suyo. He tenido que poner los threads a 3, con 8 me falla algún hilo. Quizá estaría bien que se pudiera coger por línea de comandos como parámetro.

Aún así, después de un buen rato (bastantes minutos) he recibido este mensaje:
```
[2021-08-30 19:26:54] [INFO] XML: Saltando canal encriptado 2271
[2021-08-30 19:26:54] [INFO] XML: Saltando canal encriptado 2269
[2021-08-30 19:26:54] [INFO] XML: Saltando canal encriptado 2743
[2021-08-30 19:26:54] [INFO] XML: Saltando canal encriptado 5029
[2021-08-30 19:26:54] [CRITICAL] module 'xml.etree.ElementTree' has no attribute 'indent'
```

Eso sí, ha ido descargando cosas y mostrando mucha información en el log, y el comando muestra un montón de puntos.

En cuanto a no establecer las variables de entorno, parece que ya no es necesario, lo he ejecutado en otra terminal sin ellas y también "va". A ver si el error que me da ahora se puede ver por qué es, pero ya tiene muy buena pinta!

**Comment by jmarcet** [comment]
Eso es porque tienes un python muy antiguo, de ahí lo del docker, que te sigo recomendando.

Aún así acabo de subir un arreglo para que no falle con python < 3.9

**Comment by jmarcet** [comment]
Y ahora el número de hilos de descarga es configurable, por defecto a 3.

Te va así todo sin tener que tocar nada?

**Comment by jesusvpct** [comment]
Perfecto! Aunque había actualizado a la 3.9 de Python después de ver tu mensaje anterior:
```
[2021-08-30 19:54:35] [INFO] Guardando la guía XMLTV: /home/jesus/guide.xml
[2021-08-30 19:54:35] [INFO] EPG de 29 canales y 8 días descargada en 7 minutos
```

**Comment by jmarcet** [comment]
BIEEEN! Por fin, me alegro.

Ahora a probar clientes. Te recomiendo los dos que comento en el proyecto, para Android.

El Kodi va bastante bien, pero tiene un error que no sé si está arreglado.

Con este proxy puedes ver un canal en diferido todo seguido, al acabar cada programa hay un mínimo corte, el TiviMate espera que se corte sólo, el OTT hace los cortes en los fines/principios exactos de programa y el Kodi IPTV Simple estaba fallando en pasar al directo cuando se finalizaba un programa.

A ver qué tal te va :smile:

**Comment by jesusvpct** [comment]
Una pregunta, he accedido a las URLs de mi máquina siguientes:
http://192.168.1.43:8888/channels.m3u
http://192.168.1.43:8888/MovistarTV.m3u
http://192.168.1.43:8888/guide.xml

Pero sólo me aparece información en la de guide.xml, las otras aparecen vacías, ¿es normal?

**Comment by jmarcet** [comment]
Ahh, claro, lo estás ejecutando manualmente, así que tienes que generar la guía.

El docker usa el script `start.sh`, en [esta línea](https://github.com/jmarcet/movistar-u7d/blob/9a0ad1dda0d24f643909567968c90da648fb2ee5/start.sh#L23) genera la guía, y ahora, que tampoco lo estaba haciendo, [aquí](https://github.com/jmarcet/movistar-u7d/blob/9a0ad1dda0d24f643909567968c90da648fb2ee5/start.sh#L26) y [aquí](https://github.com/jmarcet/movistar-u7d/blob/9a0ad1dda0d24f643909567968c90da648fb2ee5/start.sh#L26) crea los enlaces.

```
tv_grab_es_movistartv --m3u "${HOME:-/home}/MovistarTV.m3u"
ln -s MovistarTV.m3u "${HOME:-/home}/canales.m3u"
ln -s MovistarTV.m3u "${HOME:-/home}/channels.m3u"
```

**Comment by jmarcet** [comment]
He cambiado el script de inicio y los backends, ahora debería funcionar desde 0 con sólo arrancar los backends.

**Comment by jmarcet** [comment]
Coméntame si puedes qué tal te va al usarlo y gracias por hacerme ver lo roto que estaba desde hace unas semanas si lo usabas por primera vez.

**Comment by jesusvpct** [comment]
Voy a ver, ahora te digo, voy a borrar los archivos de caché y ejecutarlo desde cero.

Gracias a ti por el trabajazo!

**Comment by jesusvpct** [comment]
Vaya, ejecutnado el script movistar_epg.py vuelvo a tener el problema:
```
2021-08-30 20:49:43] [INFO] Descargando mapa de géneros
[2021-08-30 20:49:43] [INFO] Buscando el Proveedor de Servicios de Murcia
[2021-08-30 20:49:43] [DEBUG] Caché: datos del Proveedor de Servicios no encontrados
[2021-08-30 20:49:43] [DEBUG] Descargando XML de 239.0.2.129:3937
[2021-08-30 20:49:45] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[2021-08-30 20:49:45] [DEBUG] Descargando XML de 239.0.2.148:3937
[2021-08-30 20:50:21] [INFO] Ficheros XML descargados: [2_0 5_0 6_0] / [2_0 5_0 6_0]
[2021-08-30 20:50:21] [DEBUG] Caché: metadatos de la EPG no encontrados
[2021-08-30 20:50:21] [CRITICAL] 'NoneType' object is not subscriptable
```

Pero si ejecuto el `tv_grab_es_movistartv --tvheadend /home/jesus/MovistarTV.m3u --output /home/jesus/guide.xml` sí funciona, me descarga cosillas.

Lo comento por si hay algo en el otro script que no se esté llamando bien.

**Comment by jmarcet** [comment]
Tras ejecutar correctamente el grabber (para descargar la guía), no tienes el fichero `/home/jesus/.xmltv/cache/epg_metadata.json` ?

Por lo que indicas ese fichero no existe, y debería crearlo el `tv_grab` al descargar la guía.

**Comment by jmarcet** [comment]
El mensaje `metadatos de la EPG no encontrados` ya no existe en la versión actual del grabber, estás usando una versión anterior.

**Comment by jesusvpct** [comment]
He hecho git pull de nuevo, he borrado todo lo que hay en .xmltv para empezar de cero, he ejecutado `movistar_epg.py` pero me da el mensaje que te comento, sin embargo, si ejecuto `tv_grab_es_movistartv --tvheadend /home/jesus/MovistarTV.m3u --output /home/jesus/guide.xml` funciona bien

**Comment by jmarcet** [comment]
No puede dar el mensaje `metadatos de la EPG no encontrados` que lo dice justo antes de ese fallo.

Si te rompe será en otro sitio, con otro mensaje. Si es el mismo, tienes alguna otra copia del tv_grab_es_movistartv por ahí y ejecutas una u otra.

**Comment by jesusvpct** [comment]
Anda! No recordaba que los había metido en /usr/local/bin cuando lo probé la primera vez... Perdón!

**Comment by jmarcet** [comment]
Entiendo entonces que ahora te funciona bien?

**Comment by jesusvpct** [comment]
Sí, se está ejecutando. Como borro siempre la cache para hacerlo de cero y probarlo somo si fuera la primera vez, pues está en ello aún, pero de momento va bien, está descargando los EPG bien.

Gracias!

**Comment by jmarcet** [comment]
Bien, me alegro :smile:

A ver si ahora lo consigues probar del todo.

**Comment by jmarcet** [comment]
Una vez te funcione, la caché no la toques, no tendrás los 7 días completos de historial nada más empezar, así que es importante que la dejes estar.

**Comment by jesusvpct** [comment]
Lo he probado ya con el programa de Android y va bien.

Muchas gracias por todo!!!
