### ISSUE TITLE
Error Docker

### ISSUE THREAD

**Issue by David-ux-oss** [jmarcet/movistar-u7d#25]
Buenas, vaya currazo que habeís hecho.

Me decidí a probar vuestro pedazo de proyecto en una Rpi 3plus y con conexión 4g, en la rasberry esta instalado pihole y docker.

El docker compose que he modificado es:

version: '2.4'

services:
  movistar_u7d:
    # build: .
    image: registry.marcet.info/javier/movistar-u7d
    container_name: movistar_u7d
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    restart: on-failure
    network_mode: host
    volumes:
     - /etc/localtime:/etc/localtime
       #- ./:/app  
       #- HOME:/home
       #- RECORDINGS:/recordings
    environment:
     - DEBUG=1
     - EPG_THREADS=4
     - EXTRA_CHANNELS="4917 5066"
     - IPTV_BW=85000
     - IPTV_IFACE=wlan0
     - LAN_IP=192.168.1.10
     - MP4_OUTPUT=1
     - NOSUBS=1
     - RECORDING_THREADS=4
     - RECORDING_PER_CHANEL=1
     - SANIC_PORT=8888
     - SANIC_THREADS=4
     - U7D_UID=NOBODY
     - VERBOSE_LOGS=0
       #devices:
       #- /dev/dri:/dev/dri
    # cpu_shares: 8192
    # cpus: 4
    # mem_limit: 3gb
    # memswap_limit: 3gb
    #healthcheck:
    #test: ping -c 1 -W 1 www-60.svc.imagenio.telefonica.net | grep -q '172.26.22.23' && nc -vz ${SANIC_HOST} 8888
    #interval: 30s
    #timeout: 5s
    #retries: 3

       # vim: et ci pi sts=2 sw=2 ts=2

me da error al arracar el docker-compose al llegar a movistar_tvg.py

 movistar_u7d    | [2022-04-12 20:52:19] [TVG] [INFO] Movistar U7D - TVG v5.0
movistar_u7d    | [2022-04-12 20:52:19] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-12 20:52:19] [TVG] [INFO] Creando caché en /home/.xmltv/cache
movistar_u7d    | [2022-04-12 20:52:19] [TVG] [INFO] Descargando configuración del cliente
movistar_u7d    | [2022-04-12 21:17:21] [TVG] [INFO] Descargando perfil del servicio
movistar_u7d    | [2022-04-12 21:42:23] [TVG] [INFO] Descargando parámetros de configuración
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_tvg.py", line 1441, in <module>
movistar_u7d    |     asyncio.run(tvg_main())
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
movistar_u7d    |     return loop.run_until_complete(main)
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
movistar_u7d    |     return future.result()
movistar_u7d    |   File "/app/movistar_tvg.py", line 1346, in tvg_main
movistar_u7d    |     config = await mtv.get_service_config()
movistar_u7d    |   File "/app/movistar_tvg.py", line 481, in get_service_config
movistar_u7d    |     dvb_entry_point = platform["dvbConfig"]["dvbipiEntryPoint"].split(":")
movistar_u7d    | TypeError: 'NoneType' object is not subscriptable
movistar_u7d    | [2022-04-12 22:07:26] [EPG] [ERROR] Waiting 15s before trying to update EPG again [2/5]...
movistar_u7d    | [2022-04-12 22:07:42] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-12 22:07:42] [TVG] [INFO] Movistar U7D - TVG v5.0
movistar_u7d    | [2022-04-12 22:07:42] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-12 22:07:42] [TVG] [INFO] Descargando configuración del cliente
movistar_u7d    | [2022-04-12 22:32:44] [TVG] [INFO] Descargando perfil del servicio
movistar_u7d    | [2022-04-12 22:57:48] [TVG] [INFO] Descargando parámetros de configuración
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_tvg.py", line 1441, in <module>
movistar_u7d    |     asyncio.run(tvg_main())
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
movistar_u7d    |     return loop.run_until_complete(main)
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
movistar_u7d    |     return future.result()
movistar_u7d    |   File "/app/movistar_tvg.py", line 1346, in tvg_main
movistar_u7d    |     config = await mtv.get_service_config()
movistar_u7d    |   File "/app/movistar_tvg.py", line 481, in get_service_config
movistar_u7d    |     dvb_entry_point = platform["dvbConfig"]["dvbipiEntryPoint"].split(":")
movistar_u7d    | TypeError: 'NoneType' object is not subscriptable
movistar_u7d    | [2022-04-12 23:22:50] [EPG] [ERROR] Waiting 15s before trying to update EPG again [3/5]...
movistar_u7d    | [2022-04-12 23:23:07] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-12 23:23:07] [TVG] [INFO] Movistar U7D - TVG v5.0
movistar_u7d    | [2022-04-12 23:23:07] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-12 23:23:07] [TVG] [INFO] Descargando configuración del cliente
movistar_u7d    | [2022-04-12 23:48:09] [TVG] [INFO] Descargando perfil del servicio
movistar_u7d    | [2022-04-13 00:13:12] [TVG] [INFO] Descargando parámetros de configuración
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_tvg.py", line 1441, in <module>
movistar_u7d    |     asyncio.run(tvg_main())
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
movistar_u7d    |     return loop.run_until_complete(main)
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
movistar_u7d    |     return future.result()
movistar_u7d    |   File "/app/movistar_tvg.py", line 1346, in tvg_main
movistar_u7d    |     config = await mtv.get_service_config()
movistar_u7d    |   File "/app/movistar_tvg.py", line 481, in get_service_config
movistar_u7d    |     dvb_entry_point = platform["dvbConfig"]["dvbipiEntryPoint"].split(":")
movistar_u7d    | TypeError: 'NoneType' object is not subscriptable
movistar_u7d    | [2022-04-13 00:38:14] [EPG] [ERROR] Waiting 15s before trying to update EPG again [4/5]...
movistar_u7d    | [2022-04-13 00:38:31] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-13 00:38:31] [TVG] [INFO] Movistar U7D - TVG v5.0
movistar_u7d    | [2022-04-13 00:38:31] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-13 00:38:31] [TVG] [INFO] Descargando configuración del cliente
movistar_u7d    | [2022-04-13 01:03:33] [TVG] [INFO] Descargando perfil del servicio
movistar_u7d    | [2022-04-13 01:28:36] [TVG] [INFO] Descargando parámetros de configuración
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_tvg.py", line 1441, in <module>
movistar_u7d    |     asyncio.run(tvg_main())
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
movistar_u7d    |     return loop.run_until_complete(main)
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
movistar_u7d    |     return future.result()
movistar_u7d    |   File "/app/movistar_tvg.py", line 1346, in tvg_main
movistar_u7d    |     config = await mtv.get_service_config()
movistar_u7d    |   File "/app/movistar_tvg.py", line 481, in get_service_config
movistar_u7d    |     dvb_entry_point = platform["dvbConfig"]["dvbipiEntryPoint"].split(":")
movistar_u7d    | TypeError: 'NoneType' object is not subscriptable
movistar_u7d    | [2022-04-13 01:53:38] [EPG] [ERROR] Waiting 15s before trying to update EPG again [5/5]...
movistar_u7d    | [2022-04-13 01:53:55] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-13 01:53:55] [TVG] [INFO] Movistar U7D - TVG v5.0
movistar_u7d    | [2022-04-13 01:53:55] [TVG] [INFO] -----------------------
movistar_u7d    | [2022-04-13 01:53:55] [TVG] [INFO] Descargando configuración del cliente
movistar_u7d    | [2022-04-13 02:00:15] [TVG] [INFO] Descargando perfil del servicio
movistar_u7d    | [2022-04-13 02:00:15] [TVG] [INFO] Descargando parámetros de configuración
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_tvg.py", line 1441, in <module>
movistar_u7d    |     asyncio.run(tvg_main())
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
movistar_u7d    |     return loop.run_until_complete(main)
movistar_u7d    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
movistar_u7d    |     return future.result()
movistar_u7d    |   File "/app/movistar_tvg.py", line 1346, in tvg_main
movistar_u7d    |     config = await mtv.get_service_config()
movistar_u7d    |   File "/app/movistar_tvg.py", line 481, in get_service_config
movistar_u7d    |     dvb_entry_point = platform["dvbConfig"]["dvbipiEntryPoint"].split(":")
movistar_u7d    | TypeError: 'NoneType' object is not subscriptable
movistar_u7d    | Process ForkProcess-2:
movistar_u7d    | Process ForkProcess-1:
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
movistar_u7d    |     self.run()
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
movistar_u7d    |     self._target(*self._args, **self._kwargs)
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/server/runners.py", line 130, in serve
movistar_u7d    |     loop.run_until_complete(app._server_event("init", "before"))
movistar_u7d    |   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 2000, in _server_event
movistar_u7d    |     await self.dispatch(
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 191, in dispatch
movistar_u7d    |     return await dispatch
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 161, in _dispatch
movistar_u7d    |     retval = await maybe_coroutine
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 1524, in _listener
movistar_u7d    |     await maybe_coro
movistar_u7d    |   File "/app/movistar_u7d.py", line 112, in before_server_start
movistar_u7d    |     _IPTV = get_iptv_ip()
movistar_u7d    |   File "/app/mu7d.py", line 58, in get_iptv_ip
movistar_u7d    |     s.connect((IPTV_DNS, 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | /usr/local/lib/python3.10/multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
movistar_u7d    |   traceback.print_exc()
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
movistar_u7d    |     self.run()
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
movistar_u7d    |     self._target(*self._args, **self._kwargs)
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/server/runners.py", line 130, in serve
movistar_u7d    |     loop.run_until_complete(app._server_event("init", "before"))
movistar_u7d    |   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 2000, in _server_event
movistar_u7d    |     await self.dispatch(
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 191, in dispatch
movistar_u7d    |     return await dispatch
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 161, in _dispatch
movistar_u7d    |     retval = await maybe_coroutine
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 1524, in _listener
movistar_u7d    |     await maybe_coro
movistar_u7d    |   File "/app/movistar_u7d.py", line 112, in before_server_start
movistar_u7d    |     _IPTV = get_iptv_ip()
movistar_u7d    |   File "/app/mu7d.py", line 58, in get_iptv_ip
movistar_u7d    |     s.connect((IPTV_DNS, 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | /usr/local/lib/python3.10/multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
movistar_u7d    |   traceback.print_exc()
movistar_u7d    | Process ForkProcess-3:
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
movistar_u7d    |     self.run()
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
movistar_u7d    |     self._target(*self._args, **self._kwargs)
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/server/runners.py", line 130, in serve
movistar_u7d    |     loop.run_until_complete(app._server_event("init", "before"))
movistar_u7d    |   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 2000, in _server_event
movistar_u7d    |     await self.dispatch(
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 191, in dispatch
movistar_u7d    |     return await dispatch
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 161, in _dispatch
movistar_u7d    |     retval = await maybe_coroutine
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 1524, in _listener
movistar_u7d    |     await maybe_coro
movistar_u7d    |   File "/app/movistar_u7d.py", line 112, in before_server_start
movistar_u7d    |     _IPTV = get_iptv_ip()
movistar_u7d    |   File "/app/mu7d.py", line 58, in get_iptv_ip
movistar_u7d    |     s.connect((IPTV_DNS, 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | /usr/local/lib/python3.10/multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
movistar_u7d    |   traceback.print_exc()
movistar_u7d    | Process ForkProcess-4:
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
movistar_u7d    |     self.run()
movistar_u7d    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
movistar_u7d    |     self._target(*self._args, **self._kwargs)
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/server/runners.py", line 130, in serve
movistar_u7d    |     loop.run_until_complete(app._server_event("init", "before"))
movistar_u7d    |   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 2000, in _server_event
movistar_u7d    |     await self.dispatch(
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 191, in dispatch
movistar_u7d    |     return await dispatch
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 161, in _dispatch
movistar_u7d    |     retval = await maybe_coroutine
movistar_u7d    |   File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 1524, in _listener
movistar_u7d    |     await maybe_coro
movistar_u7d    |   File "/app/movistar_u7d.py", line 112, in before_server_start
movistar_u7d    |     _IPTV = get_iptv_ip()
movistar_u7d    |   File "/app/mu7d.py", line 58, in get_iptv_ip
movistar_u7d    |     s.connect((IPTV_DNS, 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | /usr/local/lib/python3.10/multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
movistar_u7d    |   traceback.print_exc()
movistar_u7d    | [2022-04-13 02:00:16] [U7D] [INFO] Server Stopped
movistar_u7d    | [2022-04-13 02:00:16] [INI] [WARNING] Unknown child process pid 9, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:19] [INI] [WARNING] Unknown child process pid 26, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:22] [INI] [WARNING] Unknown child process pid 28, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:24] [INI] [WARNING] Unknown child process pid 30, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:27] [INI] [WARNING] Unknown child process pid 32, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:29] [INI] [WARNING] Unknown child process pid 34, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:32] [INI] [WARNING] Unknown child process pid 36, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:34] [INI] [WARNING] Unknown child process pid 38, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:36] [INI] [WARNING] Unknown child process pid 40, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:39] [INI] [WARNING] Unknown child process pid 42, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:41] [INI] [WARNING] Unknown child process pid 44, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:44] [INI] [WARNING] Unknown child process pid 46, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:46] [INI] [WARNING] Unknown child process pid 48, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:49] [INI] [WARNING] Unknown child process pid 50, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:51] [INI] [WARNING] Unknown child process pid 52, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:54] [INI] [WARNING] Unknown child process pid 54, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:56] [INI] [WARNING] Unknown child process pid 56, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))
movistar_u7d    | OSError: [Errno 101] Network unreachable
movistar_u7d    | [2022-04-13 02:00:58] [INI] [WARNING] Unknown child process pid 58, will report returncode 255
movistar_u7d    | Traceback (most recent call last):
movistar_u7d    |   File "/app/movistar_u7d.py", line 501, in <module>
movistar_u7d    |     _conf = mu7d_config()
movistar_u7d    |   File "/app/mu7d.py", line 176, in mu7d_config
movistar_u7d    |     conf["LAN_IP"] = get_lan_ip()
movistar_u7d    |   File "/app/mu7d.py", line 64, in get_lan_ip
movistar_u7d    |     s.connect(("8.8.8.8", 53))

¿Os suena este error?

Muchas gracias y saludos

**Comment by jmarcet** [comment]
Hola,

Me hace gracia el **vosotros** porque soy una sola persona 😄  Con respecto al error, varias cosas.

La primera es que la imagen que te puedes bajar ya hecha, como usa el docker-compose tal como está, ahora mismo corresponde a la rama [next](https://github.com/jmarcet/movistar-u7d/tree/next) que tiene unas cuantas diferencias importantes, entre ellas la configuración, que la hace en un fichero aparte, `mu7d.conf`. Arrancar te arranca igual con el compose antiguo, las variables de entorno simplemente no las usa.

Lo segundo es que parece que la rasp no tiene conectividad con la IPTV de movistar, veo errores sucesivos de conexión con sus DNS. ¿Puedes probar a ejecutar desde la rasp `dig @172.26.23.3 telefonica.net` y así saber si la conectividad básica la tienes?

Espero tener la versión nueva lista como estable en los próximos días, en Windows he seguido teniendo que limar detalles.

**Comment by David-ux-oss** [comment]
Buenas perdona por lo de vosotros, si solo eres tu, un pedazo de crack

Esto es lo que me dice:
dig @172.26.23.3 telefonica.net

; <<>> DiG 9.11.5-P4-5.1+deb10u7-Debian <<>> @172.26.23.3 telefonica.net
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

Un saludo

**Comment by jmarcet** [comment]
Hola,

Parece que no te llega la IPTV de Movistar a la rasp, ya no sé el multicast, pero a las DNS no llegas.

 ¿Usas el router original de Movistar? ¿La tienes conectada por cable?

Con el router de serie lo tienes que conectar por cable. Si usas router propio, mírate [https://bandaancha.eu/foros/movistar](https://bandaancha.eu/foros/movistar)
