### ISSUE TITLE
don't support 32bits cpu.

### ISSUE THREAD

**Issue by tic13** [jmarcet/movistar-u7d#34]
As video applicacion a old computers that don't have x64 can run it (specially using dxva).but unfortunly the windows version in download section appear only support 64 bit cpu .

**Comment by jmarcet** [comment]
Hi @tic13,

It should work on Windows 32bits. You could install python and do a manual build, downloading [the entire source code](https://github.com/jmarcet/movistar-u7d/archive/refs/heads/master.zip) and after unpacking it, with python installed, do `pip install -r requirements-win.txt` and then `python setup.py build`. After that you'll have all the binaries I distribute which you can use. You can uninstall python at this point.

I'd have to check if I can make a 32bits Windows binary, but I don't know when I'll have time for that.

Dxva is not at all involved, the software only functions as a proxy, so it does not modify the video streams. It might be useful for the optional comskip step in recordings, although that is not even documented.

Also, be aware that this software only works with a Movistar fiber subscription, it needs access to Movistar's IPTV network.

**Comment by tic13** [comment]
Don`t much lucky. i have dowloaded the source code, python and complete all things they want in the way,c++,ffmepg.exe,mkvmerge.exe,installed anyio in python and so.But  when i execute mu7d.exe He only output:[u7d][critical] cannot be run more that once!.

same for the [epg]. And thats all.

**Comment by jmarcet** [comment]
Could you paste some logs? That happens when it can't access Movistar's IPTV network.

**Comment by tic13** [comment]
Hola, no me había dado cuenta que el proyecto era de aqui, por eso hablaba en ingles :D. No sé si te refieres a activar la opción debug del config, ya lo he hecho pero no parece hacer nada. o si hace logs no se a donde los manda.

Lo mismo es porque es el windows 7. loa 2 servicios no llegan a mostrar ni la primera línea con los guiones, sueltan directamente el mensaje de time out.

También lo he probado con un portátil a la última win 10,i7 64bits con el exe oficial , pero no tiene lan solo wifi y tampoco va, la epg se queda reintentado bajar  la guía.

**Comment by jmarcet** [comment]
Hola,

Con el router de serie (y en general para que funcione bien), el ordenador que ejecute el proxy debe estar conectado por cable al router, de otro modo no le llega el multicast del IPTV.

Con respecto a los logs, los muestra en la ventana que abre con un terminal que no debería cerrarse cuando falla, así se pueden ver bien los errores. Como alternativa puedes ejecutar el `mu7d.exe` desde un terminal directamente.

Yo sólo lo he probado con Windows 11, fácil que haya algún problema con Win7 que no he visto.

**Comment by jmarcet** [comment]
> Don`t much lucky. i have dowloaded the source code, python and complete all things they want in the way,c++,ffmepg.exe,mkvmerge.exe,installed anyio in python and so.But when i execute mu7d.exe He only output:[u7d][critical] cannot be run more that once!.
> 
> same for the [epg]. And thats all.

No había leído bien el error. ¿Qué es lo que ejecutas tú? Para un uso normal debes abrir sólo el `mu7d.exe`, y una sola vez, no se puede ejecutar varias veces en paralelo.

**Comment by tic13** [comment]
El pc está conectado al hgu eso sin problemas.

Si le doy a eso al mu7d.exe.

Es cuando hace el app.run(host=127.0.0.1") etc dentro del try cuando casca en los 2.

Pero como no conozco python no se por que(por donde empieza a ejecutarse) ,entiendo que es algo así como que levantas un servidor. Y no se porque ya no puede blockear más el archivo de la epg para uso exclusivo del proceso con el flilelocker y salta la excepción. Y lo mismo para u7d.

**Comment by tic13** [comment]
Es como que cuando se hace el run vuelve a ejecutar parte del if main, porque si quito el try y le pongo un info por ahí se queda en bucle imprimiendolo. Entonces al volverlo ejecutar vuelve a ejecutar el filelock y el archivo está cogido ya y se genera la excepción.

**Comment by jmarcet** [comment]
No tendrías que tocar el código, sólo quiero ver qué te sale, en qué Windows.

**Comment by tic13** [comment]
Pues es lo que dije, el u7d muestra
 la versión por pantalla entre los guiones y los otros 2 al ejecutarse no muestran nada más que el mensaje  de la excepción nada más no llega a ejecutarse nada ni a salir ningún otro mensaje de debug se queda eternamente ahí y ya está. 

Es decir mensaje de bienvenida, info de la dirección de iptv y los 2 mensajes de cannot be run more that once uno de la epg y otro de los u7d. Y ahí se queda. Windows 7 ultimate 32 bits.

**Comment by tic13** [comment]
De todas formas algo raro pasa. Porque he intentado levantar un servidor de prueba básico por mi cuenta del sanic, el tipico ejemplo de hola mundo que es copiar y pegar y tampoco lo he conseguido.  Intenta levantarlo y suelta un error de que los trabajadores no hacen arck o algo así y lo tira abajo. Así que asumo que si no levanta ni un hola mundo pues en este programa no los levantará tampoco.

**Comment by jmarcet** [comment]
Bien, parece claro entonces que hay algún problema de compatibilidad con el Windows 7 32bits.

No veo probable que haga pruebas con Windows 7, necesitarás algún otro hardware. En mi opinión lo más práctico es una pequeña placa estilo raspberry/orange pi conectada al router, y así usarlo después desde cualquier otro dispositivo, ya sea con wifi o cable.

**Comment by tic13** [comment]
Al final lo que he echo ha sido cogerle al portátil un adaptador lan a usb (3.0).(Es un portátil reciente un i7 con win 10 y 16gb de ram).

Pero tampoco he tenido suerte. El programa se ejecuta. El problema viene cuando intento reproducir canales  como la 1 HD o golplay HD. El videolan o el kodi comienzan a buffear casi constantemente y se pixela. Haciendo el portátil de cliente y servidor a la vez.  Ni idea de porqué, es como si no tuviera suficiente ancho de banda.

**Comment by jmarcet** [comment]
Me temo que es porque esos canales están encriptados. Se pueden escuchar pero no ver.
