### ISSUE TITLE
Error abrir u7d en Tivimate

### ISSUE THREAD

**Issue by Oztyle** [jmarcet/movistar-u7d#35]
Buenas tardes
Lo primero, agradecer tu trabajo!
Hoy me decidi a probar tu script con tivimate, y los canales en live me los abre sin problema. (si no tiene DRM, claro... Algo con lo que ya estoy peleando xD)

El problema es cuando quiero ver una emisión pasada.
Seleccione un programa anterior en tivimate, pero veo en la consola del pc que el script intenta arrancar el archivo en cuestión pero automáticamente se pone en stop, vuelve a intentarlo varias veces sin éxito.

A alguien más le pasa lo mismo? Alguna solución?

Gracias de nuevo. Un saludo

**Comment by jmarcet** [comment]
Hola,

Acabo de ver tu mensaje.

Sin ver los logs se me hace complicado poder decirte qué puede ser. La parte más complicada en cuanto a la red, el multicast, la tienes bien si puedes ver los directos.

Puedes pegar un pantallazo o captura de los logs?
