### ISSUE TITLE
hay alguna manera teniendo el servicio en colombia,  de poder acceder al m3u8 de los canales

### ISSUE THREAD

**Issue by jhonyesg** [jmarcet/movistar-u7d#37]
quiero es tener la lista m3u8, que se que sera valida en mi red con el servicio de television y internet por fibra optica en colombia, alguna ayuda, o que datos busco extraer, para tenerlo.

**Comment by jmarcet** [comment]
Hola,

Si tienes fibra e IPTV de Movistar en Colombia tal vez se pueda adaptar el código para que funcione pero no te puedo ayudar más.

Yo no te puedo facilitar ningún `m3u` que puedas usar como lista de canales, la genera el proxy en base a los datos obtenidos de tu red. Ya dentro de España los canales cambian según tu localización y paquete de IPTV contratado, imagínate en Colombia.

En la web de Movistar Colombia sólo veo referencias de TV a la `Movistar TV app` por lo que parece que no tenéis IPTV, aunque tampoco te lo puedo asegurar.

**Comment by santiagovasquez** [comment]
> quiero es tener la lista m3u8, que se que sera valida en mi red con el servicio de television y internet por fibra optica en colombia, alguna ayuda, o que datos busco extraer, para tenerlo.

lo intentaste ? si se puede o no ?
