### ISSUE TITLE
Movistar dns does not seem to be accessible

### ISSUE THREAD

**Issue by oatmealm** [jmarcet/movistar-u7d#4]
Hola,

(Hope it's OK if I ask in English, but feel free to reply in Spanish if you prefer).

Seems like nothing is happeing when I start the container with `docker-compose`, i.e. there nothing in the log. 

When I attach to a console and try to ran `start.sh` or one of the other services, I can see timeout errors. When I try to ping Movistar's DNS server, I get nothing. 

PS I'm a Movistar customer and on their network and paying for Movistar+ iptv, so I guess the stream are supposed to be accessible?

Thanks

**Comment by oatmealm** [comment]
Hola Javier, siento haber tardado tanto !

When I try from my workstation, I'm seeing this:

```
dig @172.26.23.3 telefonica.net

; <<>> DiG 9.16.21-RH <<>> @172.26.23.3 telefonica.net
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by jmarcet** [comment]
Hola @oatmealm,

Eso confirma que no tienes acceso a las DNS de Movistar.

Pero poco más te puedo decir sobre por qué.

**Comment by oatmealm** [comment]
I see. Looking at it, adding an interface for IPTV requires IPoE which the router I'm stuck with does not provide I think. It's the old router with the Observa Web UI.

**Comment by jmarcet** [comment]
IPoE?

You only need to setup the proper VLANs. If you can access internet, you already have VLAN 6 at the very least. You need VLAN 2 for IPTV. See my OpenWRT
![Screenshot_20211030_163704](https://user-images.githubusercontent.com/959055/139537906-b0d91d1b-3aa7-4bbc-baa6-834e247beae0.png)
:

**Comment by oatmealm** [comment]
Yes. What's for you is "static address" AFAIK is also called IPoE, which is not available for selection in my router's... attaching screen grab... it's an old router, which I can't even instaell OpenWRT to anymore (4MB limit).

![Kooha-10-30-2021-18-09-33](https://user-images.githubusercontent.com/68159077/139540744-735a84d6-2d04-4d78-a621-4e7bfc9d1d08.gif)

**Comment by jmarcet** [comment]
Ouch, I see. I did not remember those old bastards.

Anyhow, you need to get an original Movistar router in order to get your IPTV address. It would be quite better than what you seem to be using.

**Comment by jmarcet** [comment]
Although, hold on, you probably can set it up as a bridge and do all the VLAN handling and PPPoE authentication in the computer,

**Comment by oatmealm** [comment]
I'll look at it. I have a raspberry 4 attached as my home media server, but it sounds too complicated !??!

I'd like to get my own router in fact, rather than a Movistar router, unless you recommend? Can I reflash it with openwrt? I was thinking about getting my own, like Turris Omnia which I'm using back home.

**Comment by jmarcet** [comment]
Hehe, that's a different league :smile: I use an old i7-3770 with 16GB, an Intel I350-T4 board, 4x3TB and 1x12TB drives and my own OpenWRT builds.
In [this case](https://www.amazon.es/gp/product/B078JKF674/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) and with [this refrigerator](https://www.amazon.es/gp/product/B0849SJMCW/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1) it also looks awesome :smile: 

It works as my router, my NAS and a server appliance. I had never been so happy with my router, I should have done the switch way earlier.

It consumes 70W unless it is building something and it is able to saturate even wifi6 links with ease.

It boots from an NVME drive (using a modded BIOS), and in 20s my entire docker stack is running.

With dual boot it is safe to try experimental changes and in case of an issue you return to the other partition.

I share the builds I use, with generic drivers and no configuration [here](https://openwrt.marcet.info/latest/targets/x86/64/)

And [here](https://github.com/jmarcet/dockers) you can see my stack of docker-composes, this proxy is included in the [multimedia compose](https://github.com/jmarcet/dockers/blob/github/multimedia/docker-compose.yml)

**Comment by jmarcet** [comment]
Of course, that router has no wifi. At the moment I'm still using a [Unifi nanoHD](https://amzn.to/2XY7f3s) which works really really well. I manage it with the [Unifi Controller](https://github.com/jmarcet/dockprom/blob/ccde1284dddf0da0560154844949d813a5aa2312/docker-compose.yml#L198) and with [unifipoller](https://github.com/jmarcet/dockprom/blob/ccde1284dddf0da0560154844949d813a5aa2312/docker-compose.yml#L227) I get [prometheus metrics](https://github.com/jmarcet/dockprom/blob/ccde1284dddf0da0560154844949d813a5aa2312/prometheus/prometheus.yml#L40), with which I have pretty neat [Grafana](https://github.com/jmarcet/dockprom/blob/master/grafana/provisioning/dashboards/unifipoller-client-insights.json) [dashboards](https://github.com/jmarcet/dockprom/blob/master/grafana/provisioning/dashboards/unifipoller-uap-insights.json)

I recently upgraded my laptop's wifi to [Intel AX210](https://amzn.to/3msfE8F) and I am now able to use 160Mhz channels, it still tops at 750mbps, but it's stable 650-750 unlike with 80Mhz where it drifted a little bit more.

Last, I got a [Xiaomi AX3600](https://amzn.to/3nCrgFG), 8021.11ax, to upgrade from the Unifi which is 802.11ac, but it is a work in progress, no ready yet to substitute it.

**Comment by oatmealm** [comment]
Wow. What a setup! I'm much less ambitios. I have a Raspberry which I take with me when I travel, and I have everything setup there, though not even close to your elaborate solution!

**Comment by jmarcet** [comment]
Hehe, I know :smile: 

But the idea was that if you're thinking about getting a Turris Omnia, you might as well consider transforming some x86 box in case you have one lying around, even if it is a tad old, and the performance might surprise you.

**Comment by oatmealm** [comment]
Yea. Got it. I have just an old mac mini and couple of old apple tv, which are not good for anything. The MacMin 1st generation is PowerPC 4 which even though can run linux ... (is there an OpenWRT port!??!?!?!?!) is a pain in the arse to flush. Just booting from USB is a pain to start.

**Comment by jmarcet** [comment]
You might be able to get Linux running but a stable openwrt install will be too much work, it does not make sense in your case. You need something which you can start using quickly, so as you see fit, a Turris Omnia would be a great one as far as I have read about it.

Anyhow, if you want to access IPTV, you also need a Movistar router, just to find out your ip address.
