### ISSUE TITLE
Alerta en MAC  Docker - IPTV de Movistar no detectado

### ISSUE THREAD

**Issue by santiagovasquez** [jmarcet/movistar-u7d#40]
Hola, al compilar en mac con docker todo se ejecuta correctamente, estoy conectado a mi red wifi de movistar con fibra y modem de movistar (tengo todos los servicios de movistar hogar fibra)

pero los mensajes me muestra lo siguiente:
movistar_u7d  | [2024-05-19 01:53:58] [INI] [INFO] =================
movistar_u7d  | [2024-05-19 01:53:58] [INI] [INFO] Movistar U7D v5.2
movistar_u7d  | [2024-05-19 01:53:58] [INI] [INFO] =================
movistar_u7d  | [2024-05-19 01:53:58] [INI] [INFO] IPTV address: 192.168.64.2
movistar_u7d  | [2024-05-19 01:53:59] [EPG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 01:53:59] [EPG] [INFO] Movistar U7D - EPG v5.2
movistar_u7d  | [2024-05-19 01:53:59] [EPG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 01:53:59] [EPG] [WARNING] Missing channels data! Need to download it. Please be patient...
movistar_u7d  | [2024-05-19 01:54:00] [TVG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 01:54:00] [TVG] [INFO] Movistar U7D - TVG v5.2
movistar_u7d  | [2024-05-19 01:54:00] [TVG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 01:54:00] [TVG] [INFO] Creando caché en /home/.xmltv/cache
movistar_u7d  | [2024-05-19 01:54:00] [TVG] [INFO] Descargando configuración del cliente, parámetros de configuración y perfil del servicio
movistar_u7d  | [2024-05-19 02:19:04] [TVG] [CRITICAL] IPTV de Movistar no detectado
movistar_u7d  | [2024-05-19 02:19:07] [EPG] [ERROR] [2/3]...
movistar_u7d  | [2024-05-19 02:19:08] [TVG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 02:19:08] [TVG] [INFO] Movistar U7D - TVG v5.2
movistar_u7d  | [2024-05-19 02:19:08] [TVG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 02:19:08] [TVG] [INFO] Descargando configuración del cliente, parámetros de configuración y perfil del servicio
movistar_u7d  | [2024-05-19 02:44:11] [TVG] [CRITICAL] **IPTV de Movistar no detectado**
movistar_u7d  | [2024-05-19 02:44:14] [EPG] [ERROR] [3/3]...
movistar_u7d  | [2024-05-19 02:44:14] [TVG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 02:44:14] [TVG] [INFO] Movistar U7D - TVG v5.2
movistar_u7d  | [2024-05-19 02:44:14] [TVG] [INFO] -----------------------
movistar_u7d  | [2024-05-19 02:44:14] [TVG] [INFO] Descargando configuración del cliente, parámetros de configuración y perfil del servicio

-----> IPTV de Movistar no detectado ? (que me falta configurar para acceder a los canales), 
gracias de antemano, agradeceria una ayuda

**Comment by jmarcet** [comment]
@santiagovasquez

Hola, en MAC en principio no puedes usar Docker, al igual que en Windows.

En ambas plataformas hay funcionalidad experimental para que el docker use la red del host, de esa forma debería funcionar, aunque no lo he probado en ninguno de las dos.

Sin dicha funcionalidad la red que ve el docker es diferente de la del host, por lo que no es posible acceder al multicast de Movistar.

Lo que te puedo confirmar es que la rama `next` sí se puede usar en MAC directamente, es decir, sin docker. La rama `master` no lo sé, hace mucho que no la pruebo.

Me falta por arreglar un pequeño problema en Windows para publicar `next` como versión estable, por lo demás es estable al 100%.

**Comment by jmarcet** [comment]
Usarlo sin docker sí puede resultar un poco más engorroso, por la dificultad de instalar las dependencias.

```shell
git clone -b next https://github.com/jmarcet/movistar-u7d /opt/
cd /opt/movistar-u7d
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```

Y después, para usarlo, haría falta un script para activar el virtualenv y lanzarlo:

```shell
cat >/usr/local/bin/mu7d.sh<<EOF
#!/bin/bash
source /opt/movistar-u7d/.venv/bin/activate
/opt/movistar-u7d/mu7d.py
EOF
chmod +x /usr/local/bin/mu7d.sh
```

Después lo lanzas con `mu7d.sh`
