### ISSUE TITLE
Error al ejecutar 'tv_grab_es_movistartv'

### ISSUE THREAD

**Issue by jagbarcelo** [jmarcet/movistar-u7d#6]
En un servidor Ubuntu Server 20.04.3 LTS, recién instalado, limpio. Sólo con apache3-pip para poder ejecutar:
```
pip3 install -r requirements.txt
```
He seguido tus instrucciones y colocado los scripts en /usr/local/bin/ ejecutando:
```
cp movistar_u7d.py movistar_epg.py tv_grab_es_movistartv vod.py /usr/local/bin/
```
Al ejecutar el siguiente comando:
```
root@movistar-u7d:/home/# tv_grab_es_movistartv --tvheadend /home/MovistarTV.m3u --output /home/guide.xml
```
termina con el siguiente error:
```
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Traceback (most recent call last):
  File "/usr/local/bin/tv_grab_es_movistartv", line 1404, in <module>
    ElTr.indent(xml)
AttributeError: module 'xml.etree.ElementTree' has no attribute 'indent'
root@movistar-u7d:/home/.xmltv#
```

En realidad tiene muchos mas puntos. Varias páginas, durante varios minutos apareciendo puntos... y finalmente termina con ese error .

Parece que el problema está en:

https://github.com/jmarcet/movistar-u7d/blob/c92e60cb183c0c5ad135ed8d39a5c9e0fbd40069/tv_grab_es_movistartv#L1404

¿Alguna idea?

**Comment by jmarcet** [comment]
Veo que tú mismo has encontrado el problema.

En efecto, el método `ElTr.indent()` aparece en Python 3.9, así que has hecho lo mejor que podías hacer aparte de actualizar el Python.
