### ISSUE TITLE
Error movistar_epg.py

### ISSUE THREAD

**Issue by Yonoesio** [jmarcet/movistar-u7d#7]
Estoy intentando hacerlo funcionar pero no hay manera de que funcione. Al ejecutar movistar_epg.py me da este error:

> root@HomeServer:~# python3 /usr/local/bin/movistar_epg.py
> [2021-12-18 11:58:31] [5378] [INFO] Goin' Fast @ http://127.0.0.1:8889
> [2021-12-18 11:58:31] [5378] [WARNING] Missing channels data!. Need to download it. Please be patient...
> [2021-12-18 12:02:30] [5378] [INFO] Loaded fresh EPG data
> [2021-12-18 12:02:30] [5378] [INFO] Loaded Channels metadata
> [2021-12-18 12:02:32] [5378] [WARNING] 1616 53601715 not located in Cloud KeyError('episode')
> [2021-12-18 12:02:43] [5378] [ERROR] Experienced exception while trying to serve
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1051, in run
>     serve_single(server_settings)
>   File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 199, in serve_single
>     serve(**server_settings)
>   File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 146, in serve
>     loop.run_until_complete(app._server_event("init", "after"))
>   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
>   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1498, in _server_event
>     await self.dispatch(
>   File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 163, in dispatch
>     return await dispatch
>   File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 133, in _dispatch
>     retval = await maybe_coroutine
>   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1382, in _listener
>     await maybe_coro
>   File "/usr/local/bin/movistar_epg.py", line 82, in after_server_start
>     await reload_epg()
>   File "/usr/local/bin/movistar_epg.py", line 417, in reload_epg
>     await update_epg()
>   File "/usr/local/bin/movistar_epg.py", line 724, in update_epg
>     await reload_epg()
>   File "/usr/local/bin/movistar_epg.py", line 453, in reload_epg
>     await update_cloud(forced=True)
>   File "/usr/local/bin/movistar_epg.py", line 669, in update_cloud
>     merge()
>   File "/usr/local/bin/movistar_epg.py", line 660, in merge
>     for event in list(set(new_cloud[channel_id]) - set(_EPGDATA[channel_id])):
> KeyError: 4885
> [2021-12-18 12:02:43] [5378] [CRITICAL] KeyError(4885)

Lo raro es que el grabber funciona y no da error.

Estoy usando Debian 11 con Python 3.9.2.

No se que mirar ya.

**Comment by jmarcet** [comment]
Puedes probar [esto](https://github.com/jmarcet/movistar-u7d/commit/6a06e3ad436a2e2945568714f584d0dd1a64225e) ?

Está en una nueva [rama](https://github.com/jmarcet/movistar-u7d/tree/yonoesio) que he creado con tu nombre.

Puede que directamente arregle el problema o por lo menos sabremos con más precisión por qué da el `KeyError`.

**Comment by Yonoesio** [comment]
Nada. No funciona.

> > root@HomeServer:/opt/movistar-u7d# python3 /opt/movistar-u7d/movistar_epg.py
> [2021-12-18 13:25:50] [20785] [INFO] Goin' Fast @ http://127.0.0.1:8889
> [2021-12-18 13:25:50] [20785] [INFO] Loaded fresh EPG data
> [2021-12-18 13:25:50] [20785] [INFO] Loaded Channels metadata
> [2021-12-18 13:26:03] [20785] [ERROR] Experienced exception while trying to serve
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1051, in run
>     serve_single(server_settings)
>   File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 199, in serve_single
>     serve(**server_settings)
>   File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 146, in serve
>     loop.run_until_complete(app._server_event("init", "after"))
>   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
>   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1498, in _server_event
>     await self.dispatch(
>   File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 163, in dispatch
>     return await dispatch
>   File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 133, in _dispatch
>     retval = await maybe_coroutine
>   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1382, in _listener
>     await maybe_coro
>   File "/opt/movistar-u7d/movistar_epg.py", line 82, in after_server_start
>     await reload_epg()
>   File "/opt/movistar-u7d/movistar_epg.py", line 453, in reload_epg
>     await update_cloud(forced=True)
>   File "/opt/movistar-u7d/movistar_epg.py", line 666, in update_cloud
>     merge()
>   File "/opt/movistar-u7d/movistar_epg.py", line 657, in merge
>     for event in list(set(new_cloud[channel_id]) - set(_EPGDATA[channel_id])):
> KeyError: 4885
> [2021-12-18 13:26:03] [20785] [CRITICAL] KeyError(4885)

**Comment by jmarcet** [comment]
Iba a darte más instrucciones de cómo continuar pero no tiene sentido.

El motivo de que te falle es que intentas acceder a contenido de un canal encriptado. [Aquí](https://github.com/jmarcet/movistar-u7d/blob/1f86cbfe381d66883ab1f765e249b6f94d1d23ba/tv_grab_es_movistartv#L52) puedes ver la lista de los canales que son indexados y tratados por el proxy. Como puedes ver el 4885 no está en la lista.

Puedes añadirlo a continuación y lo tendrás indexado, dejará de darte problemas, pero entiendo que estará encriptado.

Si estoy equivocado, te agradezco que me lo digas.

**Comment by Yonoesio** [comment]
Estoy probando. 

Otra duda. Con el grabber original podía generar una lista completa de todos los canales. Cambiaba una variable a "ALL" y se generaba. Con tu grabber esa opción no funciona?

**Comment by jmarcet** [comment]
Bien, pero es todo con un sentido práctico. Poder podría indexar todo, en sí no hay diferencia entre la información que llega de los canales encriptados y de los canales en abierto, pero ya que el video encriptado es de poca utilidad, opté por filtrarlos.

El código está todo aquí y creo que es relativamente fácil de seguir, si quieres modificar lo que veas oportuno, haces un fork y todo tuyo.
