### ISSUE TITLE
tail the log on first time

### ISSUE THREAD

**Issue by accountgit** [jmarcet/movistar-u7d#8]
In start.sh there is a race condition depending on the speed of the start of the services.

tail -f will follow the current file, but of for some reason it's not started yet (because the device it's slow) tail will not work and will crash the container and never start.

Should be 
tail -F "${_tvgrab_log}" or with some sleep previously.

**Comment by jmarcet** [comment]
Thanks for the input.

I'm willing to change it but I fail to see how the race might happen.

The log is reset, i.e., removed and recreated in [line 7](https://github.com/jmarcet/movistar-u7d/blob/9ed46c5ea70bcf2afecb4b2b93696ab8f7d89f68/start.sh#L7), before the services are started.

I'm curious, how could the race happen?

**Comment by accountgit** [comment]
Just exactly because of that, if the device it's slow maybe could start and background services slower (ionice will "delay" the io) that the tail that will open a missing file, with -F with follow by name and reopen it.

**Comment by jmarcet** [comment]
I'd really like to see it happening.

Basically you're saying:

```
touch some.log; tail -f some.log
```

Can fail due to a race condition.

It has nothing to do with the services started in the background, hence I do not understand how a race can happen.

Can you show me some proof of how you're hitting it? You've made me really curious.

**Comment by jmarcet** [comment]
Anyhow, since there was a possible permission issue, I've fixed it, together with the change you are requesting.

It does not harm anything either.

Thanks for the feedback.
